MetabolicAtlas/MetabolicAtlas

frontend/src/components/Repository.vue, frontend/src/components/SearchTable.vue
remove search for accents, it should not impact the results since the tables contain only English data
=> slow vue good table MA-753

frontend/src/App.vue, frontend/src/components/About.vue, frontend/src/components/CompareModels.vue, frontend/src/components/Documentation.vue, frontend/src/components/Explorer.vue, frontend/src/components/Home.vue, frontend/src/components/Loader.vue, frontend/src/components/Repository.vue, frontend/src/components/Resources.vue, frontend/src/components/SearchTable.vue, frontend/src/components/explorer/GemBrowser.vue, frontend/src/components/explorer/InteractionPartners.vue, frontend/src/components/explorer/gemBrowser/Gene.vue, frontend/src/components/explorer/interactionPartners/CytoscapeTable.vue
@e0 is this more in line with what you had in mind?
=> widen content frame until widescren MA-772 

frontend/src/components/SearchTable.vue, frontend/src/components/explorer/gemBrowser/GemSearch.vue, frontend/src/components/explorer/gemBrowser/ReactionTable.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue, frontend/src/data-mappers/hmr-closest-interaction-partners.js, frontend/src/helpers/chemical-formatters.js
could not tested component with the reaction equation missing
=> fix: reversibility state of reaction MA-856

api/src/endpoints/neo4j.js, api/src/neo4j/index.js, api/src/neo4j/queries/map.js, frontend/src/api/maps.js, frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/mapViewer/MapSearch.vue, frontend/src/store/modules/maps.js
Note that the map search algorithm, similar to the other searches, does not work like before so some tuning might be needed.
=> feat: neo4j map endpoints MA-869

api/src/neo4j/queries/map.js, frontend/src/App.vue, frontend/src/components/Explorer.vue, frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/src/components/explorer/mapViewer/MapsListing.vue, frontend/src/components/explorer/mapViewer/Svgmap.vue, frontend/src/components/explorer/mapViewer/ThreeDviewer.vue, frontend/src/store/modules/maps.js, frontend/src/style/vars.scss
In this PR the aim is to refactor/drastically improve the layout of the Map Viewer on both mobile and desktop views. Any remaining bugs, eg the 2D map not showing up on mobile, should be reported in MA-897 and resolved separately.
=> update the style of the map viewer layout MA-385 

api/src/neo4j/queries/metabolite.js, frontend/src/components/explorer/gemBrowser/Metabolite.vue
This PR addresses the fetching of incorrect external ids, and adds a picture of the metabolite from ChEBI.
=> feat: metabolite pics

README.md
Improving the README for Metabolic Atlas local deployment
=> feat: improve Readme MA-834

api/src/neo4j/queries/map.js, docker-compose-local.yml, frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/mapViewer/MapsListing.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
For testing locally please use the following branches in the related repositories:
- https://github.com/MetabolicAtlas/data-files/tree/feat/custom-maps
- https://github.com/MetabolicAtlas/neo4j-data-generation/tree/feat/custom-maps
Then you should be able to see a test custom SVG map for `Human-GEM`.
=> feat: add support for custom SVG maps MA-733

frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/src/components/explorer/mapViewer/MapSearch.vue
Fixing the bug that the search bar on the 2D map can not type in text.
=> fix: 2D search bar MA-927

frontend/src/App.vue, frontend/src/components/explorer/MapViewer.vue, frontend/src/style/vars.scss
- increase size of logos
- change layout with logos equally spaced and centered on the first row, and the copyright notice on a row under
- update WCPR logo link
Also decided to make the copyright text short for mobile view as well as I thought it looked cleaner
=> feat: improve footer MA-812

.github/workflows/codeql-analysis.yml
This PR integrates CodeQL through a GH Action, which then automatically highlights issues in the `Security` tab of the repository.
=> feat: code analysis

frontend/package.json, frontend/src/components/explorer/gemBrowser/Compartment.vue, frontend/src/components/explorer/gemBrowser/Gene.vue, frontend/src/components/explorer/gemBrowser/Metabolite.vue, frontend/src/components/explorer/gemBrowser/Reaction.vue, frontend/src/components/explorer/gemBrowser/Subsystem.vue, frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/src/helpers/utils.js, frontend/src/main.js, frontend/yarn.lock
This PR closes https://github.com/MetabolicAtlas/MetabolicAtlas/issues/579
Note that the issue originally intended to target more pages but it is not clear what the best approach is for pages with multiple entities, so this has been broken off into a [new issue](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/607).
=> feat: improve "Findability on the Web" for gem browser pages MA-675

README.md
Please have a look and see if the CII badge position in the README.md is desirable and review the answers at https://bestpractices.coreinfrastructure.org/en/projects/4276. Feel free to update answers as you see fit.
=> docs: add CII best practice badge

frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
This closes #613.
Please try this out and let me know if you have any thoughts on how to further improve the UI/UX.
=> feat: make the toggle and data panels sticky in the map viewer's sidebar

api/src/neo4j/queries/gene.js
This closes https://github.com/MetabolicAtlas/private-issues/issues/107
=> feat: add list of compartments to gene details for the HPA endpoint

frontend/src/components/explorer/mapViewer/Svgmap.vue
This closes https://github.com/MetabolicAtlas/private-issues/issues/14
=> fix: SVG maps not loading on mobile 

api/src/neo4j/queries/interactionPartners.js, frontend/src/components/SearchTable.vue, frontend/src/components/explorer/InteractionPartners.vue, frontend/src/components/explorer/gemBrowser/Metabolite.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue, frontend/src/helpers/chemical-formatters.js, frontend/src/store/modules/interactionPartners.js
=> fix: interaction partners title formatting

frontend/src/components/explorer/mapViewer/Svgmap.vue, frontend/src/store/modules/maps.js
=> fix: clear error message map is found

api/yarn.lock, frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/yarn.lock
This PR aims to resolve security issues reported by GitHub's dependabot. Instead of updating specific dependencies, all dependencies have been updated.
=> chore: update dependencies

frontend/src/components/explorer/mapViewer/MapsListing.vue, frontend/src/components/explorer/mapViewer/Svgmap.vue, frontend/src/components/explorer/mapViewer/ThreeDviewer.vue, frontend/src/helpers/mapViewer.js
This PR closes #678 
Please play around with different maps in http://localhost/explore/Human-GEM/map-viewer/?dim=3d and verify that everything looks good
=> fix: make window scroll to coord 0,0 when loading a new 3D map in mobile view

proj.sh
This PR updates the Docker compose syntax to the latest version. Deploying to `dev` went smooth.
=> fix: use new docker compose commands

frontend/src/App.vue, frontend/src/components/explorer/gemBrowser/GemSearch.vue, frontend/src/style/vars.scss
This PR closes #734 
model in the vue store is updated after model change in the quick search
**Fixed buggy behavior**  
Two buggy behaviors described in the issue #734 are fixed.
**Checklist**
=> fix: update model in the store after model change

proj.sh
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/139.
Make sure the docker compose project name is always the same.
This is a small PR and the dev team has already validated the changes.
=> feat: make sure the same project name is used when deploying

frontend/src/components/explorer/MapViewer.vue
https://github.com/MetabolicAtlas/MetabolicAtlas/pull/794#discussion_r767685700
=> refactor: clearer language

frontend/src/components/Documentation.vue
This PR closes #806
The Documentation of the Data overlay is updated to meet with the new requirement for the custom data
The example custom data in the Documentation has been updated as well. 
**Testing**  
See the Data overlay section in the Documentation page
It is probably better to make the requirement of the first column header case insensitive.
**Checklist**
=> fix: update the Documentation for custom data of Data overlay 

docker-compose.yml, proj.sh
This PR closes #824
Added CHOSEN_ENV as exported global variable to `proj.sh` since this is required both by `proj.sh` and `docker-compose.yml`
**Testing**  
Try to run all commands in `proj.sh`to make sure everything is functional
**Checklist**
=> fix: broken proj.sh

api/.eslintrc.js, api/jest.config.js, api/package.json, api/test/compartments.test.js, api/test/crossReference.test.js, api/test/dataOverlay.test.js, api/test/gemComparison.test.js, api/test/genes.test.js, api/test/hpa.test.js, api/test/integratedModels.test.js, api/test/interactionPartners.test.js, api/test/jest.setup.js, api/test/maps.test.js, api/test/metabolites.test.js, api/test/reactions.test.js, api/test/search.test.js, api/test/subsystems.test.js, api/test/svgThumbnail.test.js, api/test/util.js, api/yarn.lock, docker-compose-local.yml, git_hooks/pre-commit
This PR closes #780.
This PR adds jest integration for the `api` as well as a series of tests focusing on verifying data from various endpoints.
**Testing**  
- Run the following after sourcing 'proj.sh', rebuilding, and starting the project: `ma-exec api yarn test`
Currently the tests are relatively basic but ensures some basic checks for most of the endpoints. Please let me know if there is any test that you think we should add.
**Checklist**
=> feat: verify api data

README.md
This PR closes #831 .
Added a line including contact email for reporting vulnerabilities.
Reading the issue description for #831, I initially thought this was about us needing to provide a report/document of the project's vulnerabilities upon request. I then read the section on the CII badge website and it sounds like that we just need to provide a contact email for others who want to report a potential vulnerability. It also states that "This MAY be the same as its bug reporting process. ", which is already covered under the `CONTRIBUTING` document. Just wanted to mention this here in case I misread the description.
**Checklist**
=> docs: add info about reporting potential vulnerabilities

README.md
This PR closes #851.
Add commands about testing, formatting, and linting to README.
**Checklist**
=> docs: add commands about testing, formatting, and linting

frontend/src/content/news.json
This PR relates to #839 and closes #690.
Added news for Omics Integration course, Gotbin workshop and release 2.3.
**Testing**  
- Relative urls that can be reused both for production and local testing: `/about/news`
**Checklist**
=> chore: 2.3 news

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR closes #894.
Update PR template to include DoD and feature issue template to include Acceptance Criteria.
- Did not update section [Creating a PR](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/CONTRIBUTING.md#creating-a-pr) in CONTRIBUTE.md with information regarding fulfilling the DoD, felt like it might make it a bit too much for new contributors. Do you agree?
- I replaced **Describe the solution you would like** with **Acceptance Criteria** in the feature issue template because I feel like they overlap. Legit?
=> chore: dod and acceptance criteria

frontend/src/content/news.json
This PR relates to #922 
Added news for the release 2.4
**Testing**  
=> chore: add news for the release 2.4

frontend/src/components/explorer/gemBrowser/Gene.vue, frontend/src/components/explorer/gemBrowser/Metabolite.vue, frontend/src/components/explorer/gemBrowser/Reaction.vue, frontend/src/components/explorer/gemBrowser/Subsystem.vue, frontend/src/helpers/utils.js
This PR closes #754.
For reactions, metabolites, and genes, full names of compartments and subsystems are now included in the meta description.
For subsystems, full names of compartments are now included in the meta description.
**Testing**  
Please look at the meta description for different reactions, metabolites, genes, and subsystems. The ones included in the screenshots are:
- `/explore/Human-GEM/gem-browser/reaction/MAR06245`
- `/explore/Human-GEM/gem-browser/metabolite/MAM02724m`
- `/explore/Human-GEM/gem-browser/gene/ENSG00000074416`
- …
=> fix: complete meta descriptions

api/src/neo4j/queries/search/globalSearch.js, api/src/neo4j/queries/search/modelSearch.js, frontend/src/store/modules/search.js
This PR closes #936 and was written by @e0 and @inghylt 
- Resolved bug related to UNWIND with empty list. These changes are also made in global search
- Made sure that it is not the lowest scores that is saved if multiple nodes with the same id are in the fulltext search results + refactored the related code to make it more readable to avoid future bugs. These changes are also made in global search.
- Removed redundant code from the search store. Some of it was actually redundant before the changes introduced by this PR, but the main thing is that the API now always returns a score, i.e. there should be no `undefined` cases.
**Testing**  
Search for `MAM02040c` but also other …
=> fix: model search bug

frontend/src/components/Home.vue, frontend/src/content/news.json
This PR  relates to #941 .
**Testing**  
=> chore: add news for the release 2.5

frontend/.prettierrc.json, frontend/src/components/Documentation.vue, frontend/src/components/Home.vue, frontend/src/components/Repository.vue, frontend/src/components/about/Citation.vue, frontend/src/components/about/Contact.vue, frontend/src/components/about/Introduction.vue, frontend/src/components/about/License.vue, frontend/src/components/about/Privacy.vue, frontend/src/components/about/Team.vue
This PR closes #870.
Remove unwanted spaces from html pages, set prettier to not mess with important whitespaces. See **Further comments** sections for more details and discussion.
- Removed whitespaces from a bunch of .vue files
- Set `htmlWhitespaceSensitivity` to `css`.
**Testing**  
Verify that no more unwanted whitespaces are around.
To run prettier (with `ma-exec frontend yarn run format`), make sure that `.prettierrc.json` is updated in the container.
`htmlWhitespaceSensitivity` was set to `ignore` in a21f080b80e8b59f661b064710407d0b5b947a34, to stop prettier from splitting html tags. However, this will make prettier treat all whitespaces as …
=> fix: remove unwanted whitespaces

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
This PR closes #946
Updated templates
**Testing**  
Verify that the changes look good and that there are no typos
=> feat: improve templates

frontend/src/components/CompareModels.vue, frontend/src/components/shared/ComparisonDetails.vue
This PR closes #749.
The changes aim to clarify the different numbers shown on the GEM comparison page.
- The version of the current model is shown in the comparison details box.
- A new title and some text about the historical comparisons to HMR and Recon is added.
New section title and info:
**Testing**  
Check that the text makes sense and if the links to HMR/Recon should be modified.
=> feat: provide more info on model comparisons

frontend/src/router.js
This PR closes #947 .
Redirect from `/about` to `/about/introduction`.
**Testing**  
1. Visit `/about` (enter it from the browser URL bar).
2. Verify that the `/about/introduction` page loads.
=> feat: redirect from /about to /about/introduction

api/yarn.lock, frontend/yarn.lock
This PR closes #977.
Compilation of Dependabot PRs.
Handling of other Dependabot alerts that did not have generated PRs.
Dismissed due to false flag (no longer vulnerable):
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/46
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/47
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/48
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/49
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/50
Left alone (related to vue-cli, which is planned to be replaced):
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/38
- …
=> fix: dependabot updates

frontend/src/components/Documentation.vue, frontend/src/components/about/Resources.vue, frontend/src/content/about.js
This PR closes #904.
Added a link and subsection for related resources on the documentation page.
**Testing**  
1. Visit `/documentation#related-resources`.
2. Click the `about page section` link.
3. Verify that the `/about/resources` page loads.
This satisfies the acceptance criteria but does not address [this suggestion](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/904#issuecomment-1062926745). Personally I don't feel that the are necessary although they could be nice to have. Please feel free to add the changes directly to this branch or leave …
=> feat: add link and and sub-section for related resources

frontend/src/api/gems.js, frontend/src/components/CompareModels.vue, frontend/src/components/Documentation.vue, frontend/src/components/Explorer.vue, frontend/src/components/ExternalDb.vue, frontend/src/components/Home.vue, frontend/src/components/NotFound.vue, frontend/src/components/Repository.vue, frontend/src/components/SearchTable.vue, frontend/src/components/about/Citation.vue, frontend/src/components/about/Elixir.vue, frontend/src/components/about/Resources.vue, frontend/src/components/explorer/GemBrowser.vue, frontend/src/components/explorer/InteractionPartners.vue, frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/gemBrowser/Compartment.vue, frontend/src/components/explorer/gemBrowser/Metabolite.vue, frontend/src/components/explorer/gemBrowser/Subsystem.vue, frontend/src/components/explorer/gemBrowser/Tile.vue, frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/src/components/explorer/mapViewer/MissingReactionModal.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue, frontend/src/components/explorer/mapViewer/Svgmap.vue, frontend/src/components/shared/ComparisonDetails.vue, frontend/src/components/shared/ComparisonMatrix.vue, frontend/src/components/shared/GemContact.vue, frontend/src/components/shared/References.vue, frontend/src/content/messages.js, frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue
This PR closes #873 .
All occurrences of `<br>` tags have been replaced. 
**Testing**  
Please browse through the relevant pages for the changed occurrences. Use `Human-GEM` for the model specific pages. Providing full instructions for each occurrence is not included as the time required to compose it would be disproportionate for this issue. 
Effort has been taken to keep the vertical spacing unchanged, although there are some instances where they have changed. For example on the `/explore` page, above `2. Select a tool:`. The changes are so that the vertical spacing is consistent as much as possible, specifically with Bulma in consideration (see relevant …
=> refactor: replace usages of br

api/src/neo4j/queries/relatedReactions.js, frontend/src/api/europepmc.js, frontend/src/api/gems.js, frontend/src/components/explorer/InteractionPartners.vue, frontend/src/store/modules/maps.js, frontend/src/store/modules/search.js
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/34.
- Removed `TODO` comments from code.
- Added [a comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/812#issuecomment-1128633785) to #812
- Created https://github.com/MetabolicAtlas/MetabolicAtlas/issues/991
**Testing**  
Only comments have been removed in this PR so there should be no noticeable changes to the user. Some `TODO`s were removed without creating an issue. I found them to be non-issues but please let me know if you think differently and I'm happy to create new issues for them.
=> chore: remove TODO comments

CONTRIBUTING.md, README.md
This PR relates to #963.
- Updated CONTRIBUTING.md
**Testing**  
Please read through the changes and see if they look good
=> feat: update to follow the new branching strategy

.gitignore, docker-compose-local.yml, docker-compose-remote.yml, docker-compose.yml, env-local.env.sample, pg/scripts/init-schema.sql, pg/scripts/seed-data.sql, pg/scripts/seed-mock-data.sql, proj.sh
This reverts commit 36644e7e8e79c672d077cbd3a0c4576a608839a1, reversing
changes made to e065ab8efb21378389e95f0a6a703b9fd3b955de.
This is the follow-up PR to as mentioned here: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1018#issue-1264795280 and is related to #1008.
=> chore: revert "Merge pull request #1018 from MetabolicAtlas/chore/revert-postgresql-changes

api/package.json, api/src/endpoints/enzymeDb.js, api/src/endpoints/index.js, api/src/endpoints/neo4j.js, api/src/enzymeDb/compound.js, api/src/enzymeDb/crossReferencesMapping.js, api/src/enzymeDb/db.js, api/src/enzymeDb/ec.js, api/src/enzymeDb/enzyme.js, api/src/enzymeDb/index.js, api/src/enzymeDb/reaction.js, api/src/neo4j/queries/idInModels.js, api/yarn.lock, docker-compose.yml, frontend/src/api/enzymeDb.js, frontend/src/api/idInModels.js, frontend/src/components/IdInModels.vue, frontend/src/components/enzymeDb/Compound.vue, frontend/src/components/enzymeDb/DetailsPage.vue, frontend/src/components/enzymeDb/EC.vue, frontend/src/components/enzymeDb/EnzymesTable.vue, frontend/src/components/enzymeDb/Reaction.vue, frontend/src/components/explorer/gemBrowser/ExtIdTable.vue, frontend/src/helpers/utils.js, frontend/src/router.js, frontend/src/store/index.js, frontend/src/store/modules/enzymeDb.js, frontend/src/store/modules/idInModels.js, pg/scripts/delete-db.sql, pg/scripts/init-schema.sql
This PR closes #1014 .
- Update PostgreSQL schema.
- Add API endpoints for enzymeDB, `enzyme` as well as supplementary data `compound`, `ec`, `reaction`.
- Add page in frontend that displays the entity (`compound`, `ec`, or `reaction`) details as well as listing the related `enzymes`.
- Update the cross references page to accommodate for IDs that are not found in the `neo4j` database.
**Testing**  
1. Visit an entity's details page. For example:
- `/enzymedb/compound/C00002`
- `/enzymedb/ec/2.5.1.18`
- `/enzymedb/reaction/R00006`
2. …
=> feat: enzyme db details

frontend/src/components/gotEnzymes/DetailsPage.vue, frontend/src/components/gotEnzymes/EnzymesTable.vue
This PR closes #1024.
- Adds Download button to the GotEnzyme table
- The resulting tsv file contains the same information as shown in the current enzyme table.
**Testing**  
Navigate to `gotenzymes/compound/C00003` and test the Download button. Please also try other searches. 
=> feat: enzyme download button

frontend/src/components/gotEnzymes/EnzymesTable.vue, frontend/src/components/gotEnzymes/Landing.vue
This PR updates the documentation for GotEnzymes thus closing #1034.
edit: I also spotted a tiny bug on the layout of the _Landing_ page, it had to do with a missing class, so I opted to commit it to the same PR rather than having a separate one. Since the page is copied from `Home.vue`, it was easy to figure out the missing piece.
**Testing**  
- Instructions on how to test: go to the landing page
=> chore: update documentation for GotEnzymes

pg/scripts/init.sql
This PR closes #1067 and is related to #1062.
- Update `input_data`.
- Add primary key to genes table and use single file for import.
**Testing**  
1. Replace the `input_data` with the latest updated one.
2. Visit `/gotenzymes/` and search for a gene, for example `zwf`. Verify that the response is relatively fast (hopefully under `1s`, for comparison it takes about `10s` on the dev server atm).
3. Visit a gene's details page, for example `/gotenzymes/gene/zwf`. Verify that the response is relatively fast (hopefully under `1s`, for comparison it takes about `10s` on the dev server …
=> feat: GotEnzymes genes index

frontend/src/components/explorer/gemBrowser/GemSearch.vue, frontend/src/store/modules/search.js
This PR closes #916.
- Update the limit on GemSearch results from 5 to 10 based on feedback from advisors
- Update css to match the new limit
**Testing**  
- Play around with Gem Search (quick search) and see that everything looks correct
=> feat: update Gem Search result limit from 5 to 10

api/package.json, api/yarn.lock, frontend/yarn.lock
This PR closes #1022 
-  package updating that fixes vulnerabilities
Commits included in all five dependabot PRs in this repo are added and tests passed.
**Testing**  
=> Fix: dependabot PRs

.github/workflows/codeql-analysis.yml, .github/workflows/eslint.yml, .github/workflows/prettier.yml, api/package.json, frontend/package.json, frontend/src/components/shared/RangeFilter.vue
This PR closes  #1049 by upgrading the CodeQL action (warning existed), updating the Actions so they run on the PRs against main (thus all PRs), updating the Prettier action so that it tries to fix formatting warning/errors, and finally updating the ESLint action to also output the suggestion in line with code.
**Testing**  
- Instructions on how to test: have a look at the Actions output. If you have prettier and linting running when you make local commits, commit using --no-verify
There is the option to auto-commit Prettier fixes. It's relinquishing control, but improving the speed.
=> feat: actions updates

api/src/gotEnzymes/enzyme.js, frontend/src/components/gotEnzymes/EnzymesTable.vue
**Related issue(s) and PR(s)**
This PR closes #1086
- Remove occurrence of ko in frontend and api
**Testing**  
- Please test both `/gotenzymes/` and `/api/v2/#/GotEnzymes/gotEnzymes` and make sure everything is working as before
=> feat: remove ko

api/.eslintrc.js, api/test/dataOverlay.test.js, api/test/gemComparison.test.js, api/test/integratedModels.test.js, api/test/searchGem.test.js, api/test/searchGlobal.test.js, frontend/src/components/gotEnzymes/EnzymesTable.vue, project-words.txt
=> Test: fix api tests

api/src/gotEnzymes/compound.js, api/src/gotEnzymes/index.js, api/src/neo4j/queries/metabolite.js, frontend/public/index.html, frontend/src/components/explorer/gemBrowser/Metabolite.vue, frontend/src/components/gotEnzymes/DetailsPage.vue, frontend/src/components/gotEnzymes/EnzymesTable.vue, frontend/src/components/shared/Modal.vue, frontend/src/components/shared/RDKitImage.vue, frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue, project-words.txt
This PR closes #1096.
- Add RDKit generated image for GotEnzymes compound pages.
- Add RDKit generated image for GEM Browser metabolite pages.
**Testing**  
1. Visit `/gotenzymes/compound/C00092`, verify that an image shows up next to the info and references tables.
2. Visit `/gotenzymes/compound/C15825`, verify that **no** image shows up next to the info and references tables and the rest of the page loads normally.
3. Visit `/explore/Human-GEM/gem-browser/metabolite/MAM01637c`, verify that an image shows up next to the info table.
4. Visit …
=> feat: RDKit image for metabolite/compound pages

frontend/src/components/explorer/mapViewer/DataOverlay.vue
Old text:
New text from this PR:
=> feat: more generic data overlay text

api/src/neo4j/queries/search/modelSearch.js
This PR closes #1124.
The bug was in how the neo4j query was done, where the `mid`s would get linked to the wrong names.
**Testing**  
Search for `Retinol metabolism` in the gem search and verify that you only get each item listed once.
Please also test other cases, and inspect the neo4j query.
The same bug also appears in the global search. See `search?term=retinol+metabolism`, click the `Metabolites` tab and filter by Model, so that you only see the Human-GEM.
I started on a fix for this, but it requires some more testing.
=> fix: duplicates in gem search

pg/scripts/init.sql
This PR closes #1089.
Remove `ko` from the columns expected as input to the psql database.
**Testing**  
- A rebuild is needed due to new dependencies: make sure to [reimport GotEnzymes](https://github.com/MetabolicAtlas/MetabolicAtlas/#gotenzymes)
- Instructions on how to test: play around on GotEnzymes
=> fix: remove ko

frontend/package.json, frontend/src/components/explorer/interactionPartners/DetailsPage.vue, frontend/src/components/explorer/mapViewer/ThreeDviewer.vue, frontend/yarn.lock
This PR closes  #1128.
Add color to 3d maps without redrawing the whole graph. Also don't zoom in on selected/highlighted nodes when applying overlay.
- use new function from 3dviewer to avoid having to regenerate the whole graph
- do not center selected node when applying overlay
**Testing**  
- This uses the branch [`feat/color-individual-nodes` in 3d-viewer](https://github.com/MetabolicAtlas/3d-network-viewer/compare/main...feat/color-individual-nodes)
- To use it, do:
- 1. Change value for dependency from version number to git branch in `frontend/package.json`.
```json
"@metabolicatlas/3d-network-viewer": "MetabolicAtlas/3d-network-viewer#feat/color-individual-nodes",
```
- 2. …
=> fix: map moves on overlay

frontend/src/content/news.json
This PR closes #1212.
Added link to published poster from ECCB.
**Testing**  
=> feat: add link to eccb poster

docker-compose-remote.yml, env-local.env.sample, nginx/prod.nginx.conf
This PR closes #860.
- Added transform rules in Cloudflare, see below
- Deployed to dev based on this branch + with no `IP_FILTER` in the `env-dev.env` file
**Testing**  
Use sites such as https://seositecheckup.com/tools/noindex-tag-test and https://www.seoptimer.com/noindex-tags-checker to make sure that https://dev.metabolicatlas.org is not indexed but https://metabolicatlas.org is
Based on the summary provided in https://github.com/MetabolicAtlas/MetabolicAtlas/issues/860#issuecomment-1302342163
=> feat: remove IP filter and replace with x-robots-tag

docker-compose-remote.yml
This PR closes #1200.
Remove `cpus` allocation for remote docker containers.
**Testing**  
Make sure the following endpoints work from the dev server:
- `/api/v2/3d-network?model=FruitflyGem&version=1_2_0&type=compartment&id=mitochondria`
- `/api/v2/3d-network?model=YeastGem&version=8_6_2&type=compartment&id=cytoplasm`
Try to stress the dev server if possible and make sure pages work as usual, or at least do not fail more than the production server.
Please refer to [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1200#i …
=> chore: remove cpu allocation

api/test/gotEnzymes.test.js
This PR closes #1143.
Use search terms that return results that do not contain any duplicate scores. Reason: the order for results with the same score is not important. If this reasoning is not sound and we want to actually ensure that the order is always consistent even for the same results, please let me know. We would have to change some implementation then.
**Testing**  
1. Run the tests for `GotEnzymes` : `ma-exec api yarn test test/gotEnzymes.test.js`.
2. Repeat this several times and verify that the tests always pass.
=> fix: use search terms that produce rows with unique scores

frontend/package.json, frontend/src/components/explorer/interactionPartners/ReactionTable.vue, frontend/yarn.lock
This PR closes #1167.
Fix two bugs that prevented the search from completing.
**Testing**  
1. Visit `/explore/Human-GEM/interaction-partners/MAM02634c`.
2. Try searches that should match and filter certain results, for example `MAR0` (as mentioned in the bug description), `l-`, `sLC`, `25` etc.
3. Verify that the table updates accordingly (graying out the unmatched ones and placing them below the matched ones).
=> fix: interaction partners table search

frontend/src/content/news.json
This PR closes #1230
Release news:
> In this minor release, a number of visual bugs for the Interaction Partners and 3D Map Viewer have been fixed. Moreover, incorrectly formatted metabolite names and chemicals in reaction equations are now revised. Apart from that, the global search functionality is improved by removing the duplicated hits and finally, the overall performance of the server is improved with a setup reconfiguration so that the users will not experience unexpected timeout.
- #1207 
- #1172 
- #1176 
- #1221 
- #1107 
- #1226
- #1169 
- #1174
- https://github.com/MetabolicAtlas/3d-network-viewer/issues/59
- #1140 
- #1148 
- #1200 
- #1228 
- #1143 
- #1224 
- #1214 
- #1216 
- #1210 
- #860 
- #1133 
- …
=> chore: 3.2 release

api/Dockerfile, api/package.json, api/yarn.lock
This PR closes #774.
- Install a default font (`ttf-dejavu`) alongside `fontconfig`. (Problem before was that no fonts were installed.)
- Install other build tools to address `Pango-CRITICAL` errors.
- Update `sharp` version.
**Testing**  
1. Rebuild the `api` container: `docker-compose --env-file env-local.env -f docker-compose.yml -f docker-compose-local.yml up -d --no-deps --build api`.
2. Visit a thumbnail endpoint, for example: `/api/v2/svg-thumbnail/mitochondria?model=Human-GEM&height=300` or …
=> feat: include installation of font

docker-compose-local.yml, frontend/package.json, frontend/yarn.lock
This PR closes [3dviewer issue #65](https://github.com/MetabolicAtlas/3d-network-viewer/issues/65) together with [3dviewer PR #68](https://github.com/MetabolicAtlas/3d-network-viewer/pull/68).
Use new version of 3dviewer to enable node selection on mobile devices.
**Testing**  
- A rebuild of `frontend` is needed
- Verify that you can select nodes in IP and on the 3d map viewer, on a computer and on a mobile device
- Verify that [labels are not shown outside of the map window](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1172).
=> fix: selecting 3d nodes on mobile devices

frontend/src/components/explorer/interactionPartners/ReactionTable.vue
This PR closes #1199 .
On narrow screens and mobile devices, the styling of the reaction tables is changed so that all fields can be seen and so that the screen is not filled with white space.
Thanks to @e0 for helping out with css!
**Testing**  
- Please visit different pages from Interaction Partners, using different screen sizes, and make sure that the reaction table looks good.
This issue also includes checking the **reaction tables in the GEM Browser**. They do already have similar styling for narrow screens, see below
One could extend this PR to include the column header to each field for these tables, as for the Interaction Partners version in this PR. …
=> fix: responsive tables for reaction tables on mobile devices

frontend/src/components/shared/AppHead.vue, project-words.txt
This PR closes #1215 (it should be probably be renamed to do not index any of the dev hosts)
- Implement `<meta>` tag which is described here https://github.com/MetabolicAtlas/MetabolicAtlas/issues/860#issuecomment-1302342163
**Testing**  
Visit sites such as https://seositecheckup.com/tools/noindex-tag-test and https://www.seoptimer.com/noindex-tags-checker and test if no index is applied for https://dev.metabolicatlas.org/ and https://metatlas-dev.csbi.chalmers.se
Me and @nanjiangshu looked into this together and after a lot of testing we concluded that we also need to keep the Cloudflare settings implemented in …
=> fix: implement no index for dev server

api/src/gotEnzymes/enzyme.js, api/test/gotEnzymes.test.js
This PR closes #1197.
Use with query (common table expression) to fetch the results without `limit` in a sub query. Then return the results with `limit` from the database to the backend.
**Testing**  
1. Visit the following URLs:
- `/api/v2/gotenzymes/enzymes?filters[ec_number]=6.2.1.1&pagination[page]=1&pagination[pageSize]=50&pagination[column]=reaction_id&pagination[isAscending]=false`
- `/api/v2/gotenzymes/enzymes?filters[ec_number]=7.1.1.6&pagination[page]=1&pagination[pageSize]=50&pagination[column]=compound&pagination[isAscending]=true`
2. Verify that it does not take too long to load.
3. Visit …
=> fix: add workaround that speeds up sorting

api/package.json, api/yarn.lock
This PR closes #1263 and includes #1247 and #1252.
Updates `minimatch` and `express`.
**Testing**  
- Please test the website (or the api) as extensively as you feel like (:
=> chore: dependabot updates

proj.sh
This PR closes #1261
Add a new function to proj.sh
**Testing**  
Instructions on how to test
- `source proj.sh`
- test `build-specific` with single and multiple arguments
I wasn't sure whether I should use `container(s)` or `service(s)` in the `Available commands` section, but I went with `container(s)` since that is used in other commands 
=> feat: command to build specific container(s)

frontend/src/content/news.json
This PR closes #1277
Release news:
> In this minor release, multiple visual bugs has been fixed, both for desktop and mobile users. In addition, the response time has been improved by rewriting  database queries. Finally, the software stack has been improved through dependency updates, refactoring and build scripts.
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/784
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1199
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1262
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1256
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/774
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1239
- https://github.com/MetabolicAtlas/3d-network-viewer/issues/65
- …
=> chore: 3.3 release

api/src/endpoints/dataOverlay.js, frontend/src/components/Documentation.vue
This PR closes #1105 
- Add documentation about example dataOverlay files
- Add endpoint for fetching example dataOverlay data
**Testing**  
- Visit the map viewer and test these files: obs! the reactions example file gave me errors, will need to check with PO
=> Add endpoint and examples of data overlay files

.github/workflows/prettier.yml, frontend/src/components/Documentation.vue
issue 
This PR closes #1301.
This is a known issue and the suggested solution is to change to Prettier version 4.3 istead of 4.2 in the Github workflow file.
Changed to Prettier 4.3 in the workflow file for Prettier.
**Testing**  
=> fix: adding new version of Prettier

frontend/src/components/explorer/mapViewer/DataOverlayValidation.vue, frontend/src/content/messages.js
This PR closes #1286. 
Removed a check for MIME type of uploaded data overlay files, as the MIME type set by browsers is unreliable [(background)](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1286#issuecomment-1456963756)
- Removed MIME type check 
- Removed corresponding error message since this is no longer used. 
**Testing**  
**Note:** It is quite troublesome to get the project up and running on a Windows environment (even if using WSL). The most pragmatic thing could be to expose your normal dev environment and test it there
1. Find a computer running Windows and run the steps below
2. Visit https://developer.mozilla.org/en-US/docs/Web/API/File/type and use the demo …
=> Fix overlay file upload on Windows

ftp/prep-cert.sh, neo4j/import.sh
This PR closes #1295 
This PR makes some trivial changes to the other two shell scripts in the main repo (which I found out existed this morning).  These are precisely the same kind of issues solved in `proj.sh` yesterday, so I'm re-opening #1295 to correct the other two shell scripts too.
I'm expecting this to be fairly trivial to review and merge.
* Variables have been quoted.
* Long lines have been wrapped for readability.
* Long options have been used for self-documentation.
**Testing**  
- Instructions on how to test: `clean-stack; build-stack; start-stack`
=> fix: Quote unquoted variables, use descriptive options

frontend/src/components/Repository.vue, frontend/src/components/SearchTable.vue, frontend/src/components/about/Impact.vue, frontend/src/components/explorer/MapViewer.vue, frontend/src/components/explorer/interactionPartners/DetailsPage.vue, frontend/src/components/explorer/mapViewer/DataOverlay.vue, frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue, frontend/src/helpers/utils.js, frontend/src/router.js, frontend/src/store/modules/compare.js
Reverts MetabolicAtlas/MetabolicAtlas#1304
Since things seem to have been broken by this merge we can conclude that there is no safe way to detect unused code in this code base.
=> Revert "Fix: Remove unused code"

frontend/src/components/about/Platform.vue
This PR closes #1330.
A line on _standard-GEM_ has been introduced.
The reference to the _ftINIT_ paper has been updated.
All models are now mentioned in the introduction.
Indentation has been added to the references in the _Research-driven features_.
**Testing**  
- Have a look at the About page `http://localhost/about/platform`
=> docs: update refs in About page

frontend/src/components/about/Platform.vue
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/49
Embedded contact form on the platform page. Form responses are saved to a dedicated [Google Forms page](https://docs.google.com/forms/d/1_DvRfHqu1A9hzdb6M958lTINourAFIrNQlzDJCksIZY/edit).
Addition of IFrame embedding contact form. 
**Testing**  
1. Fill in form 
2. Verify it appears in the [Google Docs spread sheet](https://docs.google.com/spreadsheets/d/1creTLbJUK_JkkMn1x2VEBI932sp2RXPKrUzPv70AHOU/edit?resourcekey#gid=2025034565) for this form (you need to be logged in to your SciLifeLab account). 
=> Google Forms-based contact form

frontend/src/content/news.json
This PR closes #1365 
* Update of all GEM models(except the Yeast GEM) in data-files
* fix: redirects for gem browser and map viewer by @jonandernovella in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1294
* fix: Address the issues mentioned in Github issue #1295 relating to the `proj.sh` dot-script by @kusalananda in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1296
* Add endpoint and examples of data overlay files by @jonandernovella in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1298
* fix: adding new version of Prettier by @KattisLej in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1312
* Fix overlay file upload on Windows by @perjo in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1297
* fix: Quote unquoted variables, use descriptive options …
=> 3.4 release

nginx/nginx.conf, nginx/prod.nginx.conf
This PR closes #1397.
The charset is enforced through the nginx config, both locally and for remote servers.
**Testing**  
See the urls mentioned in the related issue - the changes have been already deployed there.
=> fix: enforce utf-8 encoding in nginx

api/src/endpoints/repository.js
This PR closes #1392.
One could (should?) set up a custom sorting such that some entries are fixed, and others are sorted. However, given the very few changes in terms of integrated GEMs, I found it much quicker to simply disable the sorting and instead edit the source file (see [this commit](https://github.com/MetabolicAtlas/data-files/commit/b0c89bc4e19205f08f59d0acf53db82156a80295))
**Testing**  
As indicated in the issue, please check that the models in the Global search follow the user …
=> fix: list of integrated models manually defined for user preference

README.md, frontend/src/components/gotEnzymes/Landing.vue
This PR closes #1393 .
The source (raw) data for GotEnzymes has been treated differently from the other data sources. Rather than being added to the `data-files` repository, it has been uploaded directly on Zenodo. I guess one could add some code to fetch the data and unzip it in `data-files`, and then move it to the destination, but I've made a trade-off by downprioritising the technical debt otherwise incurred.
**Testing**  
- Instructions on how to use these are in the commits of this PR
=> feat: add instructions on data for GotEnzymes in Readme
