MetabolicAtlas/MetabolicAtlas

- frontend/src/components/explorer/gemBrowser/MapsAvailable.vue
Even if the list of maps were limited to 4 (max number of maps listed by default) maps, the "..." button, used to show the full list of maps, was not visible.
> fix: truncated list of maps in Gem browser pages

- proj.sh
It is a bit annoying to run `build-stack` and type yes-or-no for file overwriting hundred times when there are existing data files in the directory. I added a flag "-q" for `build-stack` function so that when this flag is enabled, existing data files will be overwritten by default.
> feat: flag for force overwriting existing data file at build-stack

- api/yarn.lock
- frontend/package.json
- frontend/yarn.lock
This PR updates `axios` as a dependency of the frontend, and a `ini` as an inner dependency of the api.
> fix: vulnerabiities in js libraries

- api/src/swagger/config.yaml
Add Swagger API Docs so that users can browser the API interface, and play around with an example query.
Example entry names or IDs are added in the description.
> feat: configure Swagger API MA-865

- frontend/src/components/explorer/mapViewer/DataOverlay.vue
> fix: on-click gene expression info icon to documentation MA-704

- frontend/package.json
- frontend/yarn.lock
This pull request updates the `3d-viewer` dependency and all subsequent dependencies. The version bump is only meant to address security concerns.
> chore: update 3d-viewer dependency

- api/src/endpoints/neo4j.js
- api/src/neo4j/queryHandlers/single.js
- frontend/src/App.vue
- frontend/src/components/NotFound.vue
- frontend/src/components/explorer/GemBrowser.vue
- frontend/src/components/explorer/InteractionPartners.vue
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/gemBrowser/Compartment.vue
- frontend/src/components/explorer/gemBrowser/Gene.vue
- frontend/src/components/explorer/gemBrowser/Metabolite.vue
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/components/explorer/gemBrowser/Subsystem.vue
- frontend/src/components/explorer/mapViewer/RNAexpression.vue
- frontend/src/components/shared/ErrorPanel.vue
- frontend/src/components/shared/ExportTSV.vue
- frontend/src/helpers/messages.js
Non-existent ids in gem browser, map viewer, and interaction partners now display an error message using the `NotFound` component.
An `ErrorPanel` component is added and used in:
- specific scenarios such as failing to apply RNA levels or exporting TSV file
- general, non 404, scenarios where a web request fails
> feat: error handler for all requests MA-578

- api/src/neo4j/queries/randomComponents.js
- api/src/neo4j/queries/relatedReactions.js
This PR covers performance enhancements for the following queries:
- random components: using the `cytosol` compartment as an example, response time improvement: `~40s` -> `~1s`
- related reactions: using the `transport_reactions` subsystem as an example, response time improvement: from `~6300ms` -> `~1200ms`
> feat: db performance enhancement MA-931

- frontend/src/components/explorer/gemBrowser/Compartment.vue
Jira task: MA-926
The compartment component would not load in certain situations, this fixes that.
Steps to reproduce former buggy behavior (written by @nanjiangshu):
1. On the home page, click "Map viewer"
2. Then click "GEM Browser"
3. Then click one of the 2D or 3D Map Viewer
4. Then click "GEM Browser" again, and the server will be in the spinning mode here.
> fix: make sure compartment is requested after route change MA-926

- frontend/src/components/explorer/gemBrowser/Compartment.vue
- frontend/src/components/explorer/gemBrowser/Gene.vue
- frontend/src/components/explorer/gemBrowser/Metabolite.vue
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/components/explorer/gemBrowser/Subsystem.vue
Through this PR the pages for the model components are refactored, removing the browser focus on the search, since that functionality is requires a click now. This focus was relevant before, when the search bar was embedded in the page above the model component, always visible.
> refactor: there is no need to focus on search in GEM Browser

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
When loading a 2D map, one is expect to click on all nodes on the map: metabolites, genes and reactions, with the details of each component being shown in the sidebar.
The reaction information was not displayed, just showing as loading forever. Apparently the wrong function was called, throwing some errors in the JS console.
The fix was tested for both 2D and 3D, on several models.
> fix: show reaction details in sidebar

- frontend/src/components/Explorer.vue
Jira issue MA-940
1. Visit the `/about` page.
2. Click `Human-GEM` link in the second paragraph of the page.
3. The user is now taken to the explore page with the correct URL `/explore/Human-GEM` but the wrong model is selected. (At the time of writing, the selected one is `Fruitfly-GEM`, which is the first one listed.)
1. Visit the `/about` page.
2. Click `Human-GEM` link in the second paragraph of the page.
3. The user should now be taken to the explore page with the correct URL `/explore/Human-GEM` and the `Human-GEM` model selected.
4. Repeat steps 1-3 for `Yeast-GEM`.
> fix: make sure the linked integrated model is selected MA-940

- frontend/src/main.js
The url needs to contain the full path up until the `/piwik.js` suffix.
> fix: source url for matomo

- .gitignore
- ftp/Dockerfile
- proj.sh
Create the folder `api/repository` if it does not exist (which is the case after a fresh clone), otherwise, the command ```/bin/cp -r $DATA_FILES_PATH/ftp-models/* api/repository/``` will end up in an error.
> fix: create folder api/repository if it does not exist

- api/src/neo4j/queries/reaction.js
- frontend/package.json
- frontend/src/api/reactions.js
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
- frontend/yarn.lock
Jira issue MA-910
This PR includes the following changes:
- For the reactions page, for example `/explore/Human-GEM/gem-browser/reaction/HMR_0001`, display gene names instead of gene ids for "Gene rule".
- For the 3d map viewer, display names instead of ids on the nodes, related work: https://github.com/MetabolicAtlas/3d-network-viewer/commit/fc2a4d5b683aede007ac5bf914d3bfbec7e23798.
- For the map viewer's sidebar, when a component (gene or metabolite) node has been selected on the map, swap positions of name and id for genes and metabolites so that the names (more familiar for users) are more prominent.
This issue is originally intended to only focus on genes. For the map viewer however, both in the 3D viewer and the sidebar, the changes from id to name are applied for genes AND …
> feat: gene and metabolite names MA-910

- proj.sh
This pull request solves the problem that `generate-data` does not overwrite existing data files in the folder `neo4j/import` on the Linux system.
> fix: force copy in generate-data MA-947

- frontend/src/components/explorer/mapViewer/Svgmap.vue
Jira issue MA-598
This PR introduces the ability to pan 2D maps by using the arrow keys. During testing I found that 10 is a good unit of movement for different maps and zoom levels, but please let me if you feel like it does not work well enough. Note that you can also hold down an arrow key for continuous panning of the map.
> feat: enable panning using arrow keys for 2D maps MA-598

- docker-compose-local.yml
- docker-compose-prod.yml
- frontend/src/components/Repository.vue
When trying to download files from the GEM repository, the urls that are computed in the frontend appear to be wrong, and thus not working, potentially due to previous refactoring.
> fix: api url for files in gem repository MA-958

- api/src/neo4j/shared/formatter.js
This pull request fixes the bug that only one record is shown for the external database table. All records in one external database entry should have separate links as well. The related Jira issue is [MA-948](https://chalmersysbiocsb.atlassian.net/browse/MA-948). 
Examples to check
1. http://localhost/explore/Human-GEM/gem-browser/metabolite/m00016m
The external database `MetaNetX` should have two records 
2. http://localhost/explore/Human-GEM/gem-browser/gene/ENSG00000000419
The external database `Ensembl protein` should have four records (with the new TSV database)
> fix: correct variable name for the external db MA-948

- frontend/src/components/Home.vue
When at https://metabolicatlas.org/ and pressing Interaction Partners the component id is hardcoded to 'm02007p'. For first time users it makes more sense to use the landing page for the Interaction Partners that is similar to the GEM Browser where they can choose a random component
closes issue #580
> feat: improve first time users experience of Interaction Partners by removing hardcoded component id MA-941 

- frontend/src/components/explorer/mapViewer/DataOverlay.vue
Removed functionality to use data overlay from protein atlas for non human models, but kept the functionality to use custom gene expression data.
Note, I haven't tried using custom gene expression data for neither human or non human models, so if you have the possibility I think it would be nice to verify that everything works as intended
> feat: disable data sources for non Human GEMs MA-956

- frontend/src/components/explorer/gemBrowser/Metabolite.vue
Issue #583
Fix so no broken ChEBI images are shown
Examples:
With image
http://localhost/explore/Human-GEM/gem-browser/metabolite/CE5122_p
With broken image
http://localhost/explore/Human-GEM/gem-browser/metabolite/m02576c
With no ChEBI entry at all
http://localhost/explore/Human-GEM/gem-browser/metabolite/m02865c
Please see if the ChEBI image check is placed suitably in method setup() (line165), and that there are no undesired side effects such as slow response time
> fix: only show ChEBI image div if ChEBI image exist MA-943

- frontend/src/components/explorer/gemBrowser/Gene.vue
- frontend/src/components/explorer/gemBrowser/Metabolite.vue
This PR closes the issue #582 
DoD: the text of the button Interaction Partners should be within the frame when resizing the window size for the Genes page and Metabolites page.
Examples for testing: 
http://localhost:9080/explore/Human-GEM/gem-browser/gene/ENSG00000140905  (Genes page)
http://localhost:9080/explore/Human-GEM/gem-browser/metabolite/m02899m         (Metabolites page with ChEBI image) 
http://localhost:9080/explore/Human-GEM/gem-browser/metabolite/m02576c          (Metabolites page without ChEBI image)
Tested web-browser: Firefox, Safari and Chrome.
> fix: messy sizing of the IP button MA-942

- api/src/neo4j/queries/compartment.js
This closes #599 
For the compartment `extracellular` in Human-GEM, the response time (when testing locally) decreased from ~27s to ~0.5s. The `cytosol` compartment, which is one of the largest, takes just under 1s now.
> fix: improve cypher query for compartments so they don't get timed out

- api/src/endpoints/neo4j.js
- api/src/neo4j/index.js
- api/src/neo4j/queries/externalDb.js
- frontend/src/App.vue
- frontend/src/api/externalDb.js
- frontend/src/components/ExternalDb.vue
- frontend/src/router.js
- frontend/src/store/index.js
- frontend/src/store/modules/externalDb.js
Originally a draft to get feedback, this PR now closes #575
This PR was created by @e0 and @inghylt
> feat: page for external ids MA-918

- api/src/neo4j/queries/map.js
- frontend/src/components/explorer/mapViewer/DataOverlay.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
- frontend/src/store/modules/maps.js
This PR closes  #581
This feature informs if there are missing reactions on the map and provides a detailed list of the missing and total reactions in a popup window.
This PR was created by @nanjiangshu  and @inghylt
> feat: 2D map coverage MA-784

- .env.sample
- .gitignore
- docker-compose-local.yml
- docker-compose-prod.yml
- frontend/src/components/Documentation.vue
- ftp/Dockerfile
This PR closes #595 by using a dedicated subdomain for the ftp server, in order to set it as unproxied in the DNS settings. Moreover, since this changes the FTP host name, it was replaced by the IP of the VM. The fix was deployed and has been verified.
Potentially one could use a variable for this, but then this variable would have to be used both in Vue and in the Dockerfile.
> fix: ftp server access

- api/src/endpoints/hpaRna.js
- api/src/endpoints/neo4j.js
- api/src/endpoints/repository.js
- api/src/endpoints/swagger.js
- frontend/src/router.js
- nginx/nginx.conf
- proj.sh
This PR closes #606. Looks like this clears all the alert (see screenshot below).
For the "Prototype-polluting assignment" warnings (`CACHED_3D_NETWORKS[model][version].whole = n;`), I simply removed the custom cache for 3D maps. For servers these should already being cached by nginx now. The potential downside is that when working locally, one might need to wait longer for working with larger 3D maps. Or maybe it is good if the developer can always see the actual load time for a 3D map. If we want to make sure that 3D networks are cached when working locally I suggest we create a new issue for caching them using nginx.
> fix: code ql warnings

- frontend/src/components/explorer/mapViewer/MapSearch.vue
This PR closes the issue #592 
DoD: The color of the gene boxes on the 2D Map Viewer changes when selecting any data source for Human-GEM on the Data Overlay side bar. 
Example to check: http://localhost/explore/Human-GEM/map-viewer/glycolysis_gluconeogenesis?dim=2d&panel=1&sel=&search=&coords=-3118.87,-4443.77,0.21,0,0,500&g1=pancreas&g2=parathyroid%20gland
> fix: broken data overlay in 2D map viewer MA-592

- frontend/src/store/modules/interactionPartners.js
> fix: use id as fallback if name is not available for title in interaction partners page

- frontend/src/api/reactions.js
- frontend/src/components/explorer/gemBrowser/Reaction.vue
The PR https://github.com/MetabolicAtlas/neo4j-data-generation/pull/18 is required for this to work.
This closes #623 and closes #590.
If successful, when browsing to `/explore/Human-GEM/gem-browser/reaction/HMR_9491` for example, you should see the following section:
> fix: make sure that gene ids that are within parenthesis are parsed properly

- frontend/src/components/explorer/gemBrowser/ReactionTable.vue
- frontend/src/helpers/utils.js
This PR fixes the broken ascii symbols and links in the Reaction Tables. 
Some examples:
/explore/Human-GEM/gem-browser/metabolite/mdz_s
/explore/Human-GEM/gem-browser/metabolite/m01202c
/explore/Human-GEM/gem-browser/metabolite/m03106c
> fix: broken ascii arrows in reaction table

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/MapsListing.vue
This PR closes [#16](https://app.zenhub.com/workspaces/metabolic-atlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/16)
Description: Custom maps should not be shown in the sidebar for 3D viewer.
DoD: custom maps is shown on the sidebar for 2D map viewer (if available) but disappear when changing to 3D viewer.
> fix: disable custom map for 3D viewer

- frontend/src/App.vue
- frontend/src/components/Repository.vue
- frontend/src/components/explorer/gemBrowser/Compartment.vue
- frontend/src/components/explorer/gemBrowser/Gene.vue
- frontend/src/components/explorer/gemBrowser/MapsAvailable.vue
- frontend/src/components/explorer/gemBrowser/Metabolite.vue
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/components/explorer/gemBrowser/ReactionTable.vue
- frontend/src/components/explorer/gemBrowser/Subsystem.vue
- frontend/src/components/explorer/mapViewer/DataOverlay.vue
- frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue
This PR closes #617
Please visit http://localhost/explore/Human-GEM/gem-browser and see if each component looks good and not too different from before.
There was some workaround needed for Metabolite ChEBI images and Reaction references, I think it looks good though
No chebi
http://localhost/explore/Human-GEM/gem-browser/metabolite/m02247l
Chebi
http://localhost/explore/Human-GEM/gem-browser/metabolite/m02604c
Chebi broken link
http://localhost/explore/Human-GEM/gem-browser/metabolite/m02576c
Reaction with references
http://localhost/explore/Human-GEM/gem-browser/reaction/HMR_4882
Also, some components used  `<maps-available :id="cName" :type="type" :element-i-d="''" />` before they were refactored. I did not add element-i-d as an option to reusable component layout since maps-available …
> Refactor: gem browser component template

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/MissingReactionModal.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
This PR closes issue #648
Please test out MapViewer and see if everything is working as it should. Please try out edge cases, such as switching between 2d and 3d, selecting another map while inside 2d and 3d and so on, to see if there are any sneaky bugs I have missed.
The modal (now in a separate component called MissingReactionModal) was moved to not be a child under `<div id="mapSidebar__header"...>` to avoid the bug introduced by the new styling in commit 8f43b0df6104b255bd9f9a60b9be8b46c683bb33. Some related information is available at https://stackoverflow.com/questions/31646746/z-index-behaviour-is-different-in-chrome-to-firefox/31710969#31710969
> fix: broken missing reactions modal

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
- frontend/src/style/vars.scss
The fix proposed by @e0 has proven to work - it was tested from the dev server and Android, and locally with Firefox/Chrome and responsive mode. Since this introduced a second use of the height value, a variable was defined.
> fix: use styling to fix the height of the 3D viewer on mobile

- frontend/src/components/explorer/mapViewer/Svgmap.vue
This closes #630 
The following steps can be used to test the intended behavior of keeping the selected element card if the new map contains it and clearing it if the new map doesn't.
1. Visit `/explore/Human-GEM/gem-browser/reaction/MAR03306`.
2. Click the "2D" button next to "Beta oxidation of di-unsaturated fatty acids (n-6) (peroxisomal)".
3. Verify that the "Reaction: MAR03306" card is **in** the map viewer sidebar after the page finishes loading.
4. Click the "Peroxisome" link under "Compartment Maps".
5. Verify that the "Reaction: MAR03306" card is **still in** the map viewer sidebar after the page finishes loading.
6. Click on any other link in the list of maps, for example: "Endoplasmic reticulum".
7. Verify that the "Reaction: MAR03306" card is **no longer in** the map viewer …
> fix: clear selected element from map viewer if the new map does not contain it

- frontend/src/components/explorer/mapViewer/MapSearch.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
This closes #638 
This also fixes problems where the mouse "clicks through" the search and map controls. For example if you dragged over the search bar it would pan the map, this is no longer the behavior so interacting with the search and map controls do not interfere with the map itself.
> fix: change layout of 2d viewer (to like in 3d) and remove previous workaround fix for enabling search

- frontend/src/components/explorer/gemBrowser/Metabolite.vue
The original version created two requests in order to verify that a ChEBI image exists https://github.com/MetabolicAtlas/MetabolicAtlas/pull/589.
In this PR the refactoring is focused on triggering a single request by using the technique described in [point 2 here](https://blog.imagekit.io/how-to-handle-loading-images-that-may-not-exist-on-your-website-92e6c3c6ea63) which also resolves bugs such as mentioned in https://github.com/MetabolicAtlas/private-issues/issues/117. While it has been reported that `onerror` is deprecated for `img`, it is still a valid HTML attribute, and as commented in various forums, it is still okay to use. Since the request to ChEBI was done prior to requesting the related metabolites, the website might also appear to load faster by having this request handled in …
> refactor: show chebi image only if exists with a single request

- frontend/src/components/explorer/gemBrowser/GemSearch.vue
This closes https://github.com/MetabolicAtlas/private-issues/issues/17
1. Visit the landing page (`/`).
2. Click on the search icon in the menubar.
3. Verify that the selected model for search is `Fruitfly-GEM`, which is the first one in the list of models.
4. Dismiss the search by clicking outside the search bar.
5. Click on the `GEM Browser` link (below the hero block), which leads to the `/explore/Human-GEM/gem-browser` page.
6. Click on the search icon in the menubar.
7. Verify that the selected model for search is now `Human-GEM` instead of staying as `Fruitily-GEM`.
> fix: update the selected model for search when the global model is updated

- frontend/package.json
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
- frontend/yarn.lock
This closes #664 
This was a bit of a tricky one. Had to do a deep dive in [how to dispose things in three.js](https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects). If I understand correctly, without manually disposing things as [now implemented](https://github.com/MetabolicAtlas/3d-network-viewer/blob/main/src/met-atlas-viewer.js#L1063) in the 3d-network-viewer library, there is no automatic garbage collection for resources used in three.js and this could potentially lead to memory leak in the RAM and GPU. Hope the fixes here covered the problem and can bring much better performance to the users.
> fix: dispose 3D viewer when it's not in use

- frontend/src/components/About.vue
This PR adds conditional support for icons linking to the GitHub profile of the advisors.
> feat: add github profiles to advisors

- frontend/src/components/NotFound.vue
As a user, I want to easily understand why an ID is not found, so that I find out how to look for it, or where the problem is.
At the moment, visiting an url with a wrong identifier, for example [this](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/m00524), shows:
With the changes in this PR, it will show:
This will help clarify that the ID was not found in the selected model, which can be different than what the user intended to select.
> feat: show model in error message for component id errors

- api/src/swagger/config.yaml
This PR closes #672
Outdated ID:s are updated with their MA equivalence. Visit /api/v2/#/Metabolites, /api/v2/#/Reactions and /api/v2/#/Interaction%20Partners to try them out
> fix: update outdated example ID:s

- frontend/src/components/ExternalDb.vue
- frontend/src/components/explorer/gemBrowser/ExtIdTable.vue
This PR closes #637 
Some points of the issue may still need to be clarified, see comment in the issue #637 
Linking from the section External databases in the Gem Browser to the identifiers page has been implemented at the commit c36b1d8c, but not sure if it is the desired feature. 
For some external pages, e.g. `/identifier/HMR%202.0/m00357c`, there is not url to the real external web-page, I think it might be better to mention that the external webpage for HMR2.0 does not exist.
> feat: incorporate feedback for the identifiers page

- frontend/public/index.html
- frontend/src/components/FourOFour.vue
- frontend/src/components/Repository.vue
- frontend/src/components/Resources.vue
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/gemBrowser/Compartment.vue
- frontend/src/components/explorer/gemBrowser/GemSearch.vue
- frontend/src/components/explorer/gemBrowser/Gene.vue
- frontend/src/components/explorer/mapViewer/MapControls.vue
- frontend/src/components/explorer/mapViewer/RNALegend.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
- frontend/src/components/shared/ComparisonDetails.vue
- frontend/src/components/shared/ComparisonMatrix.vue
This PR aims to do a bit of refactoring that was spotted via #692 . It started from removing the inline CSS that was handling `padding` and `margin`, and expanded to also replace `cursor` with the corresponding classes.
> refactor: use bulma classes and scoped css where possible

- frontend/src/components/explorer/gemBrowser/Metabolite.vue
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue
This PR closes #680
That the related reactions was not refreshed was due to that the `handleCallback` method used to get related reactions for a new reaction (i.e, when clicking on the link on a related reaction) was not using the new reaction id. This bug was also occurring for related metabolites. 
`/explore/Human-GEM/gem-browser/reaction/MAR05029` was the reported example of a misbehaving reaction, but please play around in `/explore/Human-GEM/gem-browser` and choose some random reactions/metabolites to see that their related reactions/metabolites are functioning.
> fix: make handleCallback methods use the new and not old id

- frontend/src/App.vue
- frontend/src/components/explorer/GemBrowser.vue
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/gemBrowser/MapsAvailable.vue
- frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue
This PR closes #675, i.e. fixing map names taking up too much space if very long.
Some examples links to test:
/explore/Human-GEM/gem-browser/reaction/MAR08387
/explore/Human-GEM/gem-browser/metabolite/MAM03556m
/explore/Human-GEM/gem-browser/gene/ENSG00000088179
But please play around with the gem browser as well and different screen sizes to see if you can find weird cases I've missed
> fix: work break for long names in MapsAvailable.vue

- proj.sh
This PR together [PR 18](https://github.com/MetabolicAtlas/data-files/pull/18) and [PR 23](https://github.com/MetabolicAtlas/data-generation/pull/23) with closes [#124](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/124)
Description: remove the code to copy the file `hpaRna.json` when deploying the stack since it has been replaced by the file in dataOverlay.
> feat: do not copy hpaRna.json when deploying the stack

- frontend/src/components/ExternalDb.vue
This PR closes #698 
Fix the typo `detailes` and move the line `visit ... for more details` up. 
Test URL: /identifier/MetaNetX/MNXM12010
> fix: typo in the identifier page

- frontend/src/router.js
This PR closes [#123](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/123)
The following paths should successfully redirect:
- `/explore/gem-browser/human1`
- `/explore/gem-browser/human1/gene/ENSG00000088179`
- `/explore/map-viewer/human1`
- `/explore/map-viewer/human1/acyl_coa_hydrolysis?dim=3d`
- `/api` <- this was already working from before
> feat: add redirects for links that previously should have worked

- frontend/src/components/Repository.vue
- frontend/src/components/explorer/GemBrowser.vue
- frontend/src/components/explorer/InteractionPartners.vue
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/gemBrowser/ReactionTable.vue
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
This PR closes [#39](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/3d-network-viewer/39) and relates to [#725 ]
Using `v-html` for error messages, as these might contain html elements.
To test this, you can add
```
this.errorMessage = messages.unknownError;
```
at line 437 in `InteractionPartners.vue` and visit `/explore/Human-GEM/interaction-partners`.
Note that the change has been done on multiple places, so please click around / experiment to verify that it's working in all places.
> fix: use v-html for error messages

- frontend/src/components/explorer/InteractionPartners.vue
- frontend/src/components/explorer/mapViewer/DataOverlay.vue
- frontend/src/graph-stylers/hmr-closest-interaction-partners.js
This PR closes #709 
To test this PR, please use the following interaction partners page: `/explore/Human-GEM/interaction-partners/MAM01357c` to test metabolites that are included in the sample metabolomics data. Any page should work fine for transcriptomics.
Please also pay attention to the map viewer using the following page for example `/explore/Human-GEM/map-viewer/golgi_apparatus?dim=2d&panel=1&datatype=transcriptomics&datasource=hpaRna.tsv&dataSet=none`. There seems to be a difference in how the data overlay is rendered (please see comments of this PR for more details). Please let me know if the data overlay looks ok in the map viewer or if it looks similar to the one [posted by @mihai-sysbio](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/723#issuecomment-947722719).
--- …
> feat: reuse data overlay component in interaction partners page

- frontend/src/api/reactions.js
- frontend/src/api/search.js
- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/components/explorer/gemBrowser/ReactionTable.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
- frontend/src/helpers/utils.js
This PR closes #681  and relates to [improve formatting of related reactions](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/116).
Please delete options that are not relevant.
- Functionality for adding compartments and summary to equations
- Updated background of compartments, to remove grey background
See eg `/explore/Human-GEM/gem-browser/reaction/MAR01377`. The Reaction Table should not be changed, see `/explore/Human-GEM/gem-browser/gene/ENSG00000117394`.
Please test any other location which you suspect might be effected by this, or just point them out so that I can test them.
I've added the summary at the end of the equations, but I'll remove them if not wanted.
Code wise, I've tried to reuse and adapt already existing …
> feat: show compartments

- frontend/Dockerfile
- frontend/src/content/news.json
This PR prepares the news for the 2.1 release, fixes broken links in the news section and reverts the Docker image for the `frontend` container so that it is compatible with the old `node-sass` in `package.json`. It's meant as a "last PR" prior to merging #751 .
> chore: 2.1 news

- api/Dockerfile
This PR applies the same Docker image fix that was required for the `frontend` in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/757
Please delete options that are not relevant.
The node version in the `api` Dockerfile.
Attach screenshot if relevant
Deploy the stack after stopping the stack and running `docker system prune -f`.
> fix: use node 14 for api container

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/MapSearch.vue
- frontend/src/components/explorer/mapViewer/SidebarDataPanels.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
This PR closes #737
Please delete options that are not relevant.
- If visiting `/explore/:model/map-viewer/:map_id?` where the map_id only has a associated 3D map and not a 2D map as well, the map viewer will not be broken. Instead, now you can still click "Switch to 3D".
- If there is no 2D map, there will be no summary of missing ID:s shown in the Sidebar Panel in the 2D view
- If there is no 2D, the search bar is disabled for the 2D view
Please delete options that are not relevant.
1. Visit /explore/Fruitfly-GEM/gem-browser/reaction/MAR06749
2. Press Phenylalanine, tyrosine and tryptophan biosynthesis 3D
3. Press 2D
4. Press gem browser link (subsystem or reaction does not matter)
5. Press backwards button
6. Note that the error message is same as in step 3 and that you can click on …
> fix: non existing 2d map when going back to map viewer

- frontend/src/components/explorer/gemBrowser/Reaction.vue
- frontend/src/helpers/chemical-formatters.js
- frontend/src/helpers/utils.js
This PR closes [private issue #116]( https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/116) and relates to #743.
Please delete options that are not relevant.
- Line break between related reactions
- Superscripting `+` and `-` in names
Also `-` is superscripted, as can be seen here (O2-):
See eg `/explore/Human-GEM/gem-browser/reaction/MAR02041`. 
This fix affects reactions in multiple places (reaction equation, related reactions, reactions in the search results...), but should not change the `Reaction table` tsv.
To see the change in the search result, search for eg `MAR01303` in the quick search.
It would be very good if someone familiar with the api could dobule check that everything looks good (`reaction.js` and `search.js` …
> feat: improve reaction formatting

- nginx/prod.Dockerfile
This PR relates to the [private issue 139](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/139)
Set the base image to `node:14-alpine` for the nginx production Dockerfile
**Testing**  
Please follow the instructions at https://github.com/MetabolicAtlas/docs/wiki/Deployment-via-Docker to deploy the stack to the dev server. For Linux users, might need to use `docker-compose` instead of `docker compose`. see related issue #781 
**Checklist**
> fix: set the image to 14-alpine to solve the node-sass problem

- frontend/src/components/explorer/MapViewer.vue
This PR closes #736 and was created by @e0 and @inghylt 
z-index has been added to the 2D and 3D maps to make sure it is behind gem search in firefox
**Testing**  
1. Open Firefox
2. Visit /explore/Fruitfly-GEM/map-viewer/peroxisome?dim=3d&panel=0&sel=MAM03419p&search=MAM03419p&coords=0,0,1,0,0,500&datatype=None&datasource=None&dataSet=None
3. Try searching for something in quick search
Please also play around with other maps and map search options in 2D and 3D to make sure we haven't missed anything
**Checklist**
> fix: maps and mapsearch behind gemsearch in firefox as well

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/store/modules/maps.js
This PR closes #756 
Solves the issue of not being able to switch to 3D maps when there are no 2D maps, or when you end up on an invalid map page (eg `/explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d`).
1. adds a state that keeps track of whether there are available 2D maps
2. defaults to 3D when there are no 2D maps
3. disables the switch buttons when there are no 2D maps
4. allows switching to 3D when visiting a non-existing 2D map
5. allows switching to 3D before choosing map.
**Testing**  
- To test 5:
- go to `https://metabolicatlas.org/explore/Human-GEM/map-viewer?dim=2d`. Clicking `Switch to 3D` will not do anything
- on this branch …
> fix: switch to 3d

- frontend/src/components/Documentation.vue
This PR closes #738
Data Overlay documentation is rewritten to not reference a specific HPA version as this easily can go out of date
Note that [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/738#issuecomment-966336807) was fixed in #807
**Testing**  
Look at `/documentation#Data-overlay` and see if it looks good
**Checklist**
> fix: remove HPA version from Data Overlay documentation

- .gitignore
- README.md
- docker-compose-local.yml
- docker-compose-remote.yml
- docker-compose.yml
- env-local.env.sample
- frontend/src/components/explorer/MapViewer.vue
- proj.sh
This PR closes #618 by implementing a way to use a user-provided short text to decide which environment file to use, relying on that environment file to also select the appropriate Docker context.
Instead of having to manually switch the `.env`, there are now multiple environment files that can be used, with the expected pattern `env-[NAME].env`. Before, the deployment command was expecting only a Docker context. Now, it is expecting the desired `[NAME]`, using it to identify the desired `.env` file, which now also specified the Docker context. I think this way of specifying the context might require a certain Docker version.
**Testing**  
- A rebuild is needed due to new …
> feat: deploy improvements

- frontend/src/components/explorer/MapViewer.vue
This PR closes #745 
The URL in the address bar is reset to reflect the actual map shows in the Map Viewer, so that a hard refresh (ctrl-r) will not show `map not found` error
**Testing**  
Follow the steps described in the issue  #745, the buggy behavior will disappear. 
Moreover, when switching to the 2D map viewer, select e.g. `Part 4`, and then switch to 3D and then switch back to 2D, the original 2D map for `Part 4` will be restored.  
When switching to the 2D map for the first time from the 3D map viewer, the SVG map `Part 2`, which is the first element of the array `this.currentMap.svgs`,  is selected. This might be …
> fix: make consistent url when switching between 2D/3D Map Viewer for SVG maps with sub maps 

- frontend/src/api/reactions.js
This PR closes #741.
Fixes the problem with broken links to subsystems from the reaction table in the gem browser.
- Names in  `subsystem_str` are consistently separated by `;`.
**Testing**  
- Check the subsystem links in the reaction table here `explore/Yeast-GEM/gem-browser/gene/YJL167W`
- Also verify that subsystem names with `,` still work, eg here `explore/Human-GEM/gem-browser/gene/ENSG00000121691` (`Phenylalanine, tyrosine and tryptophan biosynthesis`)
As far as I can tell, the `subsystem_str` are not used outside of `ReactionTable.vue`.
**Checklist**
> fix: split subsystem links

- frontend/src/components/Documentation.vue
This PR closes #833.
Changed the target id to the correct one so the internal links pointing to it would work.
**Testing**  
1. Go to the `/documentation` page.
2. Click on the 'Metabolite page' from the Table of Contents (sidebar).
3. Verify that the page jumps to the 'Metabolite page' section.
Initially I changed the link in the ToC to `#metabolite-page`. Then I realized that it's the id that should be changed as the links pointing to it have previously been updated elsewhere in the project: https://github.com/MetabolicAtlas/MetabolicAtlas/commit/c19b424253 …
> fix: use matching id for internal links

- frontend/src/components/explorer/mapViewer/Svgmap.vue
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/141.
The data overlay level used to be displayed on mouse hover but was then broken. This PR re-enables it.
**Testing**  
1. Visit `/explore/Human-GEM/map-viewer/acylglycerides_metabolism?dim=2d&panel=1`.
2. Select a data set, for example 'adipose tissue'.
3. Mouse over genes (rectangles) on the SVG map and verify that a number is displayed.
The mouse event initialization was previously done in the `mounted` function. In this function the `componentClassName` may still not be initialized …
> fix: display data overlay level on mouse hover

- api/src/endpoints/neo4j.js
- api/src/neo4j/queries/relatedReactions.js
- frontend/src/api/reactions.js
- frontend/src/components/Documentation.vue
- frontend/src/components/explorer/gemBrowser/ReactionTable.vue
- frontend/src/store/modules/reactions.js
This PR closes #832 .
- A new param called `allCompartments` is added to the related reactions for metabolite endpoint in The API.
- The frontend is adapted to send the new param, which results in different reactions.
**Testing**  
1. Visit `/explore/Human-GEM/gem-browser/metabolite/MAM01450c`.
2. Verify that there are 25 related reactions (as shown in the first screenshot).
3. Click the "See reactions from all compartments" button.
4. Verify that the related reactions table reloads and shows 193 reactions afterwards (as shown in the second screenshot).
5. Click the "Restrict to …
> feat: add support for returning all related reactions for a metabolite

- .github/workflows/codeql-analysis.yml
- .github/workflows/prettier.yml
This PR changes workflows to run on all branches except `main`, so that bugs don't squeeze through PRs between branches which are not `develop`. Here is the relevant [documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags).
> fix: run GH Actions workflows on all branches except main

- frontend/src/components/explorer/gemBrowser/GemSearch.vue
This PR closes #729.
- Add small delay (100ms) to the blur event for the gem search. Please note that this does not delay the global search request.
- Removed usages of jQuery in this file with plain JavaScript. Not needed for this issue but I saw some related error output in Safari.
**Testing**  
1. Click the GemSearch and input `ENSG00000002587` with model as `Fruitfly-GEM`.
2. Click the "Search all integrated GEMs" button.
3. Verify that the global page loads and performs a search on `ENSG00000002587` and the gem search hides.
Please let me know if you think the jQuery stuff should not be included here.
**Checklist**
> fix: add delay for blur event

- frontend/src/components/explorer/gemBrowser/GemSearch.vue
This PR closes #771 .
The fix consists of removing the `:value="searchTermString"` of the input field, and instead relying on  `searchDebounce()` to set that variable.
**Testing**  
- Start typing, eg "ge", in the quick search field
- Wait until the search has started and then continue typing
- Note that all letters are still there when the search finishes
Also please verify that all other interactions with the input field works as expected. Eg, that moving to the global search works.
**Checklist**
> fix: fix disappearing letters in search field

- api/src/neo4j/queries/search.js
- api/test/search.test.js
This PR closes #707 and #686.
Use a combination of exact match and fuzzy match when searching.
**Testing**  
Use the quick search and see if the results are sensible. Specifically the following search terms caused problems before. You can use the web inspector to check the scoring of the search results.
1. `POLR3F`: This should have an exact match on the gene name but it was ranked 2nd. It should be ranked 1st now.
2. `Asparaginyl-Cysteinyl`: Unsure exactly what the problem is but this does not return any matches when using fuzzy match. Using exact match does return sensible results and you should see some results returned with the top ranking results having partial matches with …
> feat: improve search scoring

- api/src/neo4j/queries/search.js
- api/src/utils/utils.js
- api/test/search.test.js
- frontend/src/api/search.js
- frontend/src/components/explorer/gemBrowser/GemSearch.vue
- frontend/src/helpers/utils.js
This PR closes #764 and (probably) #884
The search term for the quick search is cleaned to avoid unexpected neo4j querying error.
1. Special characters are escaped by adding `\ `
2. The character `"` and `\` are removed since it may cause errors even after escaping- 
3. Multiple white spaces are replaced with a single space
4. the trailing white spaces are removed 
Besides, a test is added for searching of terms with special characters.
**Testing**  
Test in the quick search with searching terms e.g.  
1. `Node: rna`, 
2. `Tricarboxylic acid cycle and glyoxylate/dicarboxylate ` 
3. `°!#€€#€%&&///(/(())())=?``^ÅPOIUUYYTTRRE …
> fix: clean search term and escape bad characters for neo4j

- frontend/src/components/SearchTable.vue
This PR closes #744  and #710
1. make the NotFound message more precisely
2. Add examples in the suggested items that can be searched in the global search.
3. Changed the term `External identifiers` to `Cross references`
Show clearer message to the user when there is no hit in the global search
**Testing**  
e.g. search with `/search?term=Cytocsolacbcd`
I could not find `cross references` for subsystems and thus I have removed it from the list. Please double check.
**Checklist**
> feat: improve NotFound message in the global search

- api/src/neo4j/queries/search/globalSearch.js
- api/src/neo4j/queries/search/helper.js
- api/src/neo4j/queries/search/index.js
- api/src/neo4j/queries/search/modelSearch.js
- api/src/utils/utils.js
- api/test/search.test.js
This PR closes #705.
- Separate model search and global search code.
- Reduce response content for model search.
- Fix bug where too many metabolites may be returned, as mentioned [here](https://github.com/MetabolicAtlas/private-issues/issues/101#issuecomment-1047937655).
**Testing**  
1. Click the search icon in the nav bar and select `Human-GEM`.
2. Search for `h2o` and make sure results for `Metabolite`, `Gene`, and `Reaction` look correct.
3. Search for `peroxisom` and make sure results for `Subsystem`, and `Compartment` look correct.
- If it helps, you can use the dev or prod server to compare the search results.
- The search results for metabolites …
> feat: separate model search and global search implementation and reduce model search response content

- frontend/src/App.vue
This PR closes #857.
Updates the copyright year to the current one (as returned by javascript).
**Testing**  
Check the footer, the standard and the compact one.
Also please verify that there aren't unintended mentions of 2021 in the README.
During last refinement, we discussed different solutions for this, eg having `2018-current` instead of a specified year.
The solution I went for in this PR sets the year to the current one, and does not have to be updated. We also don't have to figure out which starting year the copyright would have. 
**Checklist**
> feat: update copyright year

- frontend/public/index.html
- frontend/src/App.vue
This PR closes #775 .
The title tag will default to `Metabolic Atlas`.
Add a default title value to `App.vue`
**Testing**  
Navigate to the GEM Browser.
Click on any reaction, metabolite, gene or subsytem.
Note that the title tag updates.
Navigate to any other part of the web page (eg `About`)
Note that the title is `Metabolic Atlas` again.
**Checklist**
> fix: set default title tag

- docker-compose-remote.yml
This PR closes #765
Limit for neo4j transaction timeout increased to make sure that time consuming global searches does not lead to 400 Bad Request.
**Testing**  
This has been tested, i.e. deployed,  on the dev machine. Following links cause error with a lower limit but work with 40 sek:
`https://dev-metatlas.csbi.chalmers.se/search?term=citric%20acid`
`https://dev-metatlas.csbi.chalmers.se/search?term=C5-branched%20dibasic%20acid%20metabolism`
But please experiment more with global search and see if everything is working correctly
A limit of the previously suggested 30 sek continued to cause 400 Bad Request for the example links above, but 40 sek seems to …
> fix: increase timeout to fix error for time-consuming global searches

- api/src/swagger/config.yaml
This PR closes #759
1. Fixed the outdated description for the interaction partners 
2. Fixed typos and grammatical errors
3. Fixed the outdated upper limit for related reactions
**Testing**  
http://localhost/api/v2/
The API for the random components does not return valid results if the optional field `componentTypes` is unfilled. 
that is the url
http://localhost/api/v2/random-components?model=HumanGem&componentTypes=%7B%7D returns a 400 error.
The url that returns a random sample of all components is either 
http://localhost/api/v2/random-components?model=HumanGem&componentTypes=
or 
http://localhost/api/v2/random-components?model=HumanGem
**Checklist**
> Fix: description in the API page

- frontend/src/layouts/explorer/gemBrowser/ComponentLayout.vue
This PR closes #819
Updated the url to a valid one
**Testing**  
Visit some of the links below and click on the link in "The complete list in JSON format..."
`http://localhost/explore/Human-GEM/gem-browser/compartment/peroxisome`
`http://localhost/explore/Human-GEM/gem-browser/compartment/endoplasmic_reticulum`
`http://localhost/explore/Human-GEM/gem-browser/compartment/cytosol`
**Checklist**
> fix: use valid url

- frontend/src/components/about/Resources.vue
This PR closes #893 
Fix the link to the API in the `about/resources` page and fixed typos
**Testing**  
Click `Access Metabolic Atlas programmatically` in the page http://localhost/about/resources and it should direct you to the API page.
The comment https://github.com/MetabolicAtlas/MetabolicAtlas/issues/893#issuecomment-1057747239 @mihai-sysbio mentioned is not related to this issue. I think it might be caused by the configuration in the `prod.nginx.conf`. As I tested, the behaviors are the same for the `prod` and `dev`
https://metabolicatlas.org/api/   not-working 
https://metabolicatlas.org/api    working 
https://dev-metatlas.csbi.chalmers.se/api/    not-working
https://dev-metatlas.csbi.chalmers.se/api …
> fix: broken link to the API in the resource page 

- frontend/src/components/NotFound.vue
This PR closes #760.
Removed top and bottom padding to avoid overflow of code elements
**Testing**  
Visit for example `/explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d` or `/explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxx?dim=2d`
- I chose not to use bulma `py` since it would need to be added for two `<code>` elements + they already had a style section so to me it made sense. Feel free to have feedback on this though
- Should I add a comment in the code regarding why the padding is 0 or is that superfluous?
**Checklist**
> fix: remove padding to avoid code element overflow

- frontend/src/content/news.json
This PR adds minor changes to the news for the release 2.4 in responding to [this commit](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/923#issuecomment-1075245589)
I was trying to merge without opening a new PR but then realized it is forbidden.
> chore: minor changes to the news 2.4 

- frontend/src/components/shared/TableOfContents.vue
This PR closes #864.
Changes for the ToC are made according to the issue description, including:
- Sticks to the top after scrolling the page down.
- Has max visible height of screen height and gets its own scroll section if it's longer than the screen height.
- Does not become sticky for mobile (smaller than `$tablet`) devices.
- Adds nested visualization for active link. The active color before `white-ter` is now used for the active parent link. The actual active link color is now `link-light`, which seems to work well with the look and feel of the rest of the ToC, for example the icon color.
**Testing**  
- …
> feat: UI and UX improvements for Table of Contents

- api/src/neo4j/queries/compartment.js
- api/src/neo4j/queries/subsystem.js
This PR closes #800.
We have [these lines](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/2d061fd4ff58e093a8748829ecdaccc8452ddae2/api/src/neo4j/queryHandlers/single.js#L20-L25) that trigger a `404` for whenever an object is empty. The problem before was that object at this point is not empty according to our definition because it has the following shape. Specifically due to the `"compartmentId": "typo"` part.
```json
{
"metabolitesCount": 0,
"reactionsCount": 0,
"genesCount": 0,
"compartmentSVGs": [
{
"compartmentId": "typo",
"compartmentSVGs": []
}
],
"subsystems": [],
"externalDbs": []
}
```
This PR fixes the cypher queries so that the object would have the following shape instead, which fits our …
> fix: make sure 404 is triggered when compartment or subsystem is not found

- api/src/neo4j/queries/search/globalSearch.js
- api/src/neo4j/queries/search/helper.js
- api/src/neo4j/queries/search/modelSearch.js
This PR closes #889.
Adapt case statement in neo4j query to use the parent node when encountering a PubmedReference node.
**Testing**  
Try searching for PMIDs, eg `11579996`, `16111821`, `18406340`, `11368003`. The result should contain Reactions, where the PMIDs can be seen in th References table at the bottom of the page.
Also please verify that the results for other types of queries haven't changed.
> fix: use parent node of pubmedreference

- nginx/prod.nginx.conf
This PR closes #911.
Both `/api/` and `/api` now redirects to `/api/v2/`.
Set these configs under `api/v2` instead of `api/`
```
limit_req zone=api_limit burst=20 nodelay;
try_files $uri @proxy_cached;
```
so that the code block doesn't block redirection from `api` (in the block below).
**Testing**  
This branch is deployed to the dev server.
Test `/api/` and `/api`.
I'm far from an nginx expert, so please verify that this does not break any intended behaviour.
> fix: redirect api/ to api/v2

- git_hooks/pre-commit
This PR closes #871.
Only files with any of the extensions `.{vue,js,html,css,ts,yaml}` will be formatted and linted.
- Filter files in precommit hook by extension
- Refactor  `pre-commit`
**Testing**  
Try to add and commit a `png` file, or any other file which should not be linted. When committing, make sure eslint skips the file.
Also verify that eslint and prettier is still run as expected when committing. 
[The documentation](https://eslint.org/docs/user-guide/configuring/ignoring-code#ignored-file-warnings) claims that files listed as ignored will be skipped, even if they are explicitly passed to eslint. For whatever reason, I can't get this to work. Instead the staged files are …
> chore: eslint ignore images

- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/DataOverlay.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
- frontend/src/store/modules/dataOverlay.js
This PR closes #935 and #789.
Changes of the overlay is kept even if the overlay bar is collapsed.
The levels / overlay is kept when switching between 2D/3D, when a new map is chosen, or if leaving the Maps and then returning.
As a consequence, issue #789 was solved.
**Testing**  
Navigate to the map viewer, open any map and then open the `Data Overlay` side bar. Add a Level.
Verify that the overlay is kept (on the map, in the dropdown, in the url) when collapsing and reopening the overlay side bar. 2D and 3D  should work the same way.
Also test that the overlay works as expected when moving around on the page.
I did not implement the optional acceptance criterion (adding some sort of …
> fix: overlay disappears on collapsing bar

- api/src/swagger/config.yaml
This PR closes #948.
Rename Swagger operation ID for interaction partners from `geneInteractionPartners` to `interactionPartners`.
**Testing**  
1. Visit `/api/v2/#/Interaction%20Partners/interactionPartners`.
2. Verify that the page scrolls to the specified endpoint/operation.
Camel case (`interactionPartners`) is used instead of pascal case (`InteractionPartners`) as specified in the issue's acceptance criteria. This is to be consistent with the rest of the page.
> docs: rename operation ID for interaction partners

- api/.eslintrc.js
- api/src/neo4j/queries/search/globalSearch.js
- api/src/neo4j/queries/search/helper.js
- api/src/neo4j/queries/search/modelSearch.js
- api/test/jest.setup.js
- api/test/search.test.js
- api/test/searchGem.test.js
- api/test/searchGlobal.test.js
This PR closes #896, created by @inghylt and @MalinAhlberg 
When searching for a metabolite name (eg "3(R)-hydroxy-(2S,6R,10)-trimethyl-hendecanoyl-CoA"), the score for the corresponding metabolite node (MAM00685p) will no longer be zero.
- Keep the connection between metabolites and compartmentalized metabolites in the neo4j queries (global and model search), so that the score can be correctly set
- adds test for this bug fix 
- in commit 9257786, use `>=` when testing for `max 50`
**Testing**  
Test searching for metabolite names and make sure they show up as first result.
Also verify that other searches work as expected, regarding both components and models.
**Further comments** …
> fix: search for metabolite names give score zero

- frontend/src/content/news.json
This PR closes #966.
Removed GEM version prefix for news section.
**Testing**  
1. Visit `/about/news` and make sure there are no version prefixes (`v*`). 
The only remaining instance of the version prefixes are found on the news page. I'm not 100% if they should even be removed here as they are not used directly after a model. I think #966  could be closed with or without this PR. Please let me know if you know of any other instances.
The [comment regarding dash between model and version number](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/966#iss …
> feat: remove GEM version prefix

- frontend/src/api/europepmc.js
- frontend/src/store/modules/europepmc.js
This PR closes #996.
- Move data formatting logic from `./frontend/src/api/europepmc.js` to `./frontend/src/store/modules/europepmc.js`.
- Use `reduce` + [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) instead of `forEach` + `try/catch` to process data.
**Testing**  
Visit a page that contains reference details from Europe PMC, for example: `/explore/Human-GEM/gem-browser/reaction/MAR03372`, and verify that the section looks and works the same as before.
It would have been helpful to identify …
> refactor: formatting logic for Europe PMC results

- proj.sh
This PR closes #816.
Removes only Metabolic Atlas specific docker items (containers, images, and volumes) instead of all docker items for the entire system.
**Testing**  
- A rebuild is needed ~~due to new dependencies~~ if you currently don't have the project stack built
1. Use the latest `proj.sh` file: `source proj.sh`.
2. (Optional) Build and start the project if necessary: `build-stack && start-stack`.
3. (Optional) If you don't have any other docker related items, add one to help the verification step. For example: `docker pull hello-world && docker run hello-world`.
4. Clean the stack: `clean-stack`.
5. Verify that the project stops running and all of the related docker …
> fix: remove only project specific docker items

- api/src/neo4j/queries/compare.js
This PR closes #823.
Use `JOIN` to optimize cypher query and remove redundant part of the query. The time taken for query went from ~1.7min to ~20s on my machine.
In plain language, we are looking for all instances of model `A` where it shares a common `ExternalDb`(Cross Reference) with model `B` and model `C`. This is satisfied by the following two lines:
```graphql
MATCH (a:${type}:${ma.model})-[:V${ma.version}]-(e:ExternalDb)-[:V${mb.version}]-(b:${type}:${mb.model})
MATCH (a)-[:V${ma.version}]-(e)-[:V${mc.version}]-(c:${type}:${mc.model})
```
The next line, while technically correct, is completely unnecessary and slowed down the query:
```graphql
MATCH (b)-[:V${mb.version}]-(e)-[:V${mc.version}]-(c)
``` …
> fix: improve performance of GEM comparison query to avoid server timeout

- .gitignore
- docker-compose-local.yml
- docker-compose-remote.yml
- docker-compose.yml
- env-local.env.sample
- pg/scripts/00-schema.sql
- pg/scripts/01-seed-mock-data.sql
- pg/scripts/init-schema.sql
- pg/scripts/seed-data.sql
- pg/scripts/seed-mock-data.sql
- proj.sh
This PR closes #1008.
- Add PostgreSQL to the project using docker.
- For the enzyme database, ddd scripts to initialize and seed the data.
**Testing**  
- A ~~rebuild~~restart (`start-stack`) is needed due to new dependencies
1. Update the `env-local.env` file and add the `POSTGRES_PASSWORD` environment variable. An example can be found in `env-local.env.sample`.
2. (Re)start the stack: `start-stack`. This should set up the new `pg` container
3. Verify that the PostgresQL container is up and running: `ma-exec pg psql -U postgres -c '\list'`.
4. Initialize the DB schema: `ma-exec pg psql -f scripts/init-schema.sql -U postgres`.
5. Add the input data files (currently incomplete). …
> feat: add PostgreSQL to the project for the enzyme database

- proj.sh
This PR closes #1041 and is related to #1023.
Adds a command to the `deploy-stack` function that makes sure the password specified in the given `*.env` file is set.
**Testing**  
1. Change the value of `POSTGRES_PASSWORD` in your `env-dev.env` file to something else.
2. Deploy to the dev server `deploy-stack dev`.
3. Verify that the `GotEnzymes` pages are working. For example `/gotenzymes/reaction/R01234`.
The way things are setup now. The command to set the password runs after the command to deploy the stack. For this to happen the `pg` container must be up and running before the password command is run. This …
> fix: make sure that the PostgreSQL password is reset after deployment

- api/src/gotEnzymes/index.js
- api/src/gotEnzymes/search.js
This PR closes #1060. Joint work with @e0.
The `.` in the EC codes are replaced by a standard character (`a`) in the psql search, so that the standard similarity score works as expected.
- Use replacement of special character to improve search results for ECs.
**Testing**  
- Try searching for example `7.1.1.1` and make sure the first hit is the exact match
- Search for `1.1.3` and see that the results are relevant
- Also try other types of searches to make sure the work as expected and that performance is not affected.
> fix: improve ec search

- frontend/src/components/SearchTable.vue
- frontend/src/components/gotEnzymes/Landing.vue
This PR closes #1035.
- Added padding to GotEnzyme landing page
- Added padding to Global Search
Added both left and right padding as I thought this looked better
**Testing**  
- Look at `/search` (with and without search results) and `/gotenzymes` at normal, ipad and mobile screen and make sure everything looks good
> feat: add padding to improve mobile view

- frontend/src/content/news.json
In this major release we provide access to the newly created database <i>GotEnzymes</i> (article under consideration). GotEnzymes contains over 25.7 million predicted enzyme turnover numbers (k<sub>cat</sub>) for +5.8 million unique sequences and 4147 compounds, across 8099 species. The values are predicted by cutting-edge artificial intelligence tools. These new data are stored in a newly-added Postgres database that is seamlessly integrated into the software stack. In addition, Metabolic Atlas has obtained an _Identifiers.org_ profile and has improved the _About_ pages.
<br> More details can be found <a href='https://github.com/MetabolicAtlas/MetabolicAtlas/releases/tag/3.0' target='_blank'>on GitHub</a> or <a href='https://zenodo.org/badge/latestdoi/53664497' target='_blank'>on …
> 3.0 release

- frontend/src/components/gotEnzymes/Landing.vue
This is a tiny PR fixing the landing page for GotEnzymes, so that it is consistent with the _News_ and release text, thus resolving  #1100.
> fix: numbers on gotenzymes landing page

- api/src/endpoints/gotEnzymes.js
- api/src/gotEnzymes/compound.js
- api/src/gotEnzymes/domain.js
- api/src/gotEnzymes/ec.js
- api/src/gotEnzymes/enzyme.js
- api/src/gotEnzymes/gene.js
- api/src/gotEnzymes/organism.js
- api/src/gotEnzymes/reaction.js
- api/src/swagger/config.yaml
This PR closes #1074.
Return `404` instead of `500` when no matches are found. Compare to `api/v2/genes/unknown?model=HumanGem`
- Return `404` when no (or multiple!) matches are found.
- The swagger doc is updated accordingly.
**Testing**  
- Try out the different api routes under `GotEnzymes` (see `api/v2/#/GotEnzymes`) with made-up ids (eg `
api/v2/gotenzymes/reactions/ueau`) and make sure that they return `404` and not `500`. This should work for  `gotenzymes/reactions`, `gotenzymes/genes`, `gotenzymes/ecs`, `gotenzymes/compounds` and `gotenzymes/organisms`.
- Also test clicking around the GotEnzymes pages (`/gotenzymes`) to make sure everything works as expected.
When multiple …
> fix: gotenzymes correct error code

- frontend/src/components/gotEnzymes/EnzymesTable.vue
- frontend/src/components/shared/ExportTSV.vue
This PR closes #1075.
Adds loader for the enzymes table.
The loader is shown when:
- a new table is being loaded
- filtering is done
- sorting is done
- next/previous page is clicked
The download button is disabled when the table is loading
**Testing**  
- To see better how the loader looks and behaves, you can add these lines
```
const sleep = ms => new Promise(r => setTimeout(r, ms));
await sleep(1000);
```
to `api/src/endpoints/gotEnzymes.js`, line 113
- Go to eg `gotenzymes/compound/C00003` and try reloading the page, sorting and filtering the columns, moving to another enzymes page etc.
> feat: gotenzymes loader

- frontend/src/components/IdInModels.vue
- frontend/src/components/Loader.vue
- frontend/src/components/NotFound.vue
- frontend/src/components/explorer/mapViewer/MissingReactionModal.vue
- frontend/src/components/shared/ComparisonMatrix.vue
- frontend/src/components/shared/RangeFilter.vue
- frontend/src/layouts/AboutLayout.vue
This PR closes #917.
- Make sure `class` or `id` is used for scoped styling.
- Remove unused `style` blocks.
**Testing**  
Please test the following pages and verify that things look the same as before. The new selectors can be found from the PR changes.
- `/identifier/KEGG/C00222`, file: `frontend/src/components/IdInModels.vue`
- `/gotenzymes/reaction/R01677`
- file: `frontend/src/components/Loader.vue` (note that it could be difficult to see the loader message if the page loads too fast)
- file: `frontend/src/components/shared/RangeFilter.vue`
- `/explore/Human-GEM/gem-browser/metabolite/123`, file: …
> feat: use class or id selectors in for scoped css

- api/src/neo4j/queries/search/modelSearch.js
- api/test/searchGem.test.js
- frontend/src/components/Documentation.vue
- frontend/src/components/explorer/gemBrowser/GemSearch.vue
- frontend/src/store/modules/search.js
This PR closes #968 and #848 
1. The results of GemSearch are sorted by score and <= limit number of top ranked results are returned. This makes sure that the parameter `limit` is more meaningful. 
2. The notification message in GemSearch is changed to `Limited to 50 results (max 10 per type)` to reflect that the limit is for all components, but when showing on the frontend, at maximum 10 per type are shown.
3. The test for GemSearch is updated to reflect that the limit is for all components.
**Testing**  
The results of GemSearch are sometimes different compared to before since some of the low scoring hits exceeding limit 50 are excluded. 
**Definition of …
> Fix: search limit inconsistency

- api/test/compartments.test.js
- api/test/integratedModels.test.js
- api/test/searchGem.test.js
- api/test/searchGlobal.test.js
This PR together with https://github.com/MetabolicAtlas/data-files/pull/32  closes #1081 
Fix the API tests to reflect the model updating. 
**Testing**  
- require the branch `feat/update-models` of the repo `data-files`
- A rebuild is needed due to updated models
The expected reaction ID at https://github.com/MetabolicAtlas/MetabolicAtlas/blob/fix/api-test-after-model-update/api/test/searchGem.test.js#L244 has been changed from  `MAR00973` to `MAR03896` since there are several top ranking hits having the same score and it is not guaranteed that the first one is always  `MAR03896`. One could write more complicated testing code to make sure one of the top …
> Fix: tests in the API due to model updating

- api/src/neo4j/queries/compartment.js
- api/src/swagger/config.yaml
This PR closes #914.
The param `full` in `/compartmets/{id}`, will be false when set to a falsy value or when left out.
- Updated the handling of the parameter
- Updated the swagger docs
**Testing**  
- Take a look at the updated swagger description
- Test that:
- `api/v2/compartments/golgi_apparatus?model=HumanGem&full=true` give full results
- `api/v2/compartments/golgi_apparatus?model=HumanGem&full` give full results
- `api/v2/compartments/golgi_apparatus?model=HumanGem` give short results
- `api/v2/compartments/golgi_apparatus?model=HumanGem&full=false` give short results
See [slack thread](https://nbisweden.slack.com/archives/C01D13EKUV7/p1663840452835189 …
> fix: use the value of the param

- frontend/package.json
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
- frontend/yarn.lock
This PR closes #1080.
- Update `3d-network-viewer` version
- Change how it is imported
**Testing**  
1. Rebuild the project (this installs the new dependency).
2. Visit a 3d map page, for example: `/explore/Human-GEM/map-viewer/alanine_aspartate_and_glutamate_metabolism?dim=3d`. Make sure it works like how it used to. Please try different things here such as zooming, rotating, searching etc.
This seems to shave about 0.6MB off the bundle size.
> chore: update 3d network viewer version

- docker-compose-remote.yml
- nginx/prod.Dockerfile
- nginx/redirector.conf
This PR closes #1157 and relates to https://github.com/MetabolicAtlas/private-issues/issues/38.
The production Dockerfile was updated, and an Nginx configuration was added to disable IPv6 (see comments below for full story).
**Testing**  
- Instructions on how to test: deploy the stack as usual to either `dev` or `prod3`
This was also researched by @MalinAhlberg and @inghylt.
In the end, there were multiple problems, mainly stemming from using Let's Encrypt certificates though a custom Docker image. This is marked for removal in https://github.com/MetabolicAtlas/private-issues/issues/38 . However, the FTP server still requires the certificates, so this functionality can only be removed …
> fix: nginx setup for deployment with ssl

- api/src/swagger/config.yaml
This PR closes #1073 .
For 1:
The problem is not only that the server response is a bit slow, but also that the browser gets unhappy with the amount of response data loaded to swagger. I did the following updates:
- changed the example value to Yeast-GEM which is slightly smaller than Human-Gem
- added a warning to the description
For 2:
- added a default, since swagger otherwise insisted to use `{}`as the standard value (not accepted by the api).
- removed the text saying that the value is optional
**Testing**  
1:
- Visit `/api/v2/#/Miscellaneous/mapListing`
- Read through the instructions and examples 
- Note the slowness of the page when the request has finished. For example, …
> fix: update swagger description

- proj.sh
This PR closes #1131.
Use `docker compose stop` instead of `docker compose kill` when running `stop-stack`. This sends a graceful shutdown message `SIGTERM` instead of `SIGKILL`.
After applying this change, I restarted the stack several times without `neo4j` failing to start, whereas before it was failing almost every other time.
This is a quick little read along with an informative but heart-breaking comic that illustrates the differences: https://linuxhandbook.com/sigterm-vs-sigkill/
**Testing**  
After `source proj.sh`, restart (`stop-stack` followed by `start-stack`) a few times and verify that `neo4j` …
> fix: use stop instead of kill to gracefully shutdown containers

- proj.sh
This PR closes #852.
- Reset docker context after deploying by: `export DOCKER_CONTEXT=default`
**Testing**  
1. Deploy to dev server: `deploy-stack dev`.
2. Verify that the docker context is reset to `default` after deployment: `docker context show`.
3. Verify that commands such as `stop-stack` no longer affects the dev server.
> fix: reset docker context after deploy

- frontend/src/helpers/chemical-formatters.js
- project-words.txt
This PR closes #1140 
This PR fixes incorrect formatting of equations as described at https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1140#issuecomment-1319249412, that is
1. incorrectly formatted number as subscript for metabolite names 
2. incorrectly formatted cations with multiple charges
The function `chemicalEquation` is now reusing the function `chemicalFormula` and thus it fixes also the problem for equations in GotEnzymes
**Testing**  
You can check if the bad formatting in the following pages are fixed
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01899r G10597
https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04110 …
> Fix: chemical formatting

- frontend/src/components/explorer/interactionPartners/DetailsPage.vue
This PR closes #1226.
Set a `z-index` value for the network viewer containers to prevent ensure they do not interfere with the stacking context of the rest of the website. For more on stacking context (`z-index`) see: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#example
**Testing**  
- Instructions on how to test (instructions stolen from @MalinAhlberg's issue description)
1. Visit `/explore/Human-GEM/interaction-partners/MAM02040r?expandedIds=&dataTypes=gene&dataSources=hpaRna.tsv&dataSets=None`.
2. Zoom in and out a bit on the map.
3. Click …
> style: set stacking context for viewer containers

- frontend/src/components/explorer/interactionPartners/DetailsPage.vue
- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
This PR closes #1221
Colors are reapplied after a node has been clicked
**Testing**  
Please visit both 3D network viewer and IP partner. Try out networks of different sizes and with multiple simultaneous overlays.
There is some lag, but IMO (and @e0:s :D) it is not a problem. The lag only annoys me a bit when applying reaction overlay on  Cytosol and Extracellular, i,e, massive networks, but since those are really too big to be of any value for researchers anyway I think it is acceptable. 
Note that there is no lag even on large networks such as `/explore/Human-GEM/interaction-partners/MAM03343c?expandedIds=MAM02039c` …
> fix: reapply colors after node has been clicked

- api/src/endpoints/neo4j.js
- api/src/neo4j/queries/interactionPartners.js
- frontend/src/components/explorer/interactionPartners/DetailsPage.vue
This PR closes  #1174.
The api will return the failing node id when calling `/interaction-partners` and `interaction-partners-expansion`.
The frontend will show the failing node id.
Api will return an error message `Invalid id xxx` when provided with an incorrect value for interaction partners
Frontend will parse and show that id
**Testing**  
- Visit Interaction Partners, eg `explore/Human-GEM/interaction-partners/MAM03769e`, and make sure you can expand nodes as expected
- Visit Interaction Partners using a bad value for the main node, eg `explore/Human-GEM/interaction-partners/nonono` and make sure that the error message makes sense
- Try adding a bad value for the expanded …
> fix: correct error message for bad value for expanded ids

- frontend/src/components/explorer/mapViewer/ThreeDviewer.vue
This PR closes #1239.
Clear loader after network is rendered.
**Testing**  
1. Visit `/explore/Human-GEM/map-viewer/cytosol?dim=3d`.
2. Verify that the network viewer shows immediately after the loader clears, without a delay showing an empty canvas.
I couldn't really notice the delay even before this fix on my machine, tested on Safari, Firefox, and Chrome. The fix I included should work in theory but I haven't fully confirmed it. Please let me know if this solves it for you.
> fix: clear loader after network is rendered

- frontend/src/components/gotEnzymes/DetailsPage.vue
- frontend/src/components/gotEnzymes/EnzymesTable.vue
- frontend/src/components/gotEnzymes/Landing.vue
This PR closes #1241 
Errors are reported when:
1. searching fails on Landing page: "unkown error"-message box popping up
2. getting a component (trying to load a Details page) fails: "Uknown component" shown at the top of the page
3. sorting, filtering or loading enzymes table fails: "unknown error"-message box popping up
Examples of scenarios above:
1.
2.
3.
**Testing**  
To test this, you can use commit c9e0d24d21f27eb0f53f2d3e372c897c7516af42 which makes the different queries to the gotenzymes api fail randomly. Then visit `/gotenzymes` and try searching, loading component pages, and interacting with the enzymes table. Make sure that:
- no errors are reported unless there are …
> fix: gotenzymes show errors

- api/src/neo4j/queries/relatedReactions.js
- api/test/metabolites.test.js
This PR closes #1262 . Many thanks to @inghylt for helping out with this!
Select distinct reactions before applying limit
**Testing**  
Go to `explore/Human-GEM/gem-browser/metabolite/MAM02040c` and check that the number of related reactions are >1000 even when switching to "See reactions for all compartments".
Please also check that the numbers for other metabolite's related reactions are the same as before.
> fix: inconsistent related reactions number

- frontend/src/components/explorer/interactionPartners/ReactionTable.vue
This PR closes #1253.
- Prevent table from being wider than the screen
- Prevent table cell content from overflowing
**Testing**  
1. Visit `/explore/Human-GEM/interaction-partners/MAM01285c`.
2. Scroll down to the reactions table and verify that the width does not exceed the screen and that the table and its contents look good. Please try on different screen widths as well.
> style: limit table and content widths

- frontend/src/components/explorer/mapViewer/MapLoader.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
This PR closes #1242 
Fixed the problem that the SVG map blinks when switching back from the 3D map viewer 
**Testing**  
Open the Map Viewer, switch between 2D and 3D and see if the SVG map blinks
Try a few examples
> fix: blinking SVG map when switching between 2D and 3D

- frontend/src/components/gotEnzymes/EnzymesTable.vue
This PR closes #1269.
Always reset the page to `1` when sorting or filtering. Please read under **Further comments** for the reasoning behind this.
**Testing**  
1. Visit an enzymes details page, for example: `/gotenzymes/reaction/R01677`.
2. Go to the bottom of the page and change the page, for example to: `20`.
3. Sort by a column, for example: `Compound`.
4. Verify that the page number displayed in the frontend as well as the `page` parameter sent to the server are both `1`.
5. Filter by a column, for example: enter `C00387` under `Compound`.
6. Verify that the page number displayed in the frontend as …
> fix: reset page to 1 when sorting or filtering

- frontend/package.json
- frontend/src/components/SearchTable.vue
- frontend/src/components/explorer/mapViewer/Svgmap.vue
- frontend/yarn.lock
This PR closes #1156.
- Rewrite jQuery instances using plain JavaScript in:
- `frontend/src/components/SearchTable.vue`
- `frontend/src/components/explorer/mapViewer/Svgmap.vue`
- Remove jQuery from the project (`frontend`)
**Testing**  
1. Visit a 2D map page, for example `/explore/Human-GEM/map-viewer/golgi_apparatus?dim=2d`.
2. Verify that the map works as before. Please try different interactions such as using data overlay, mouse hovering and clicking, toggles, search etc.
3. Visit a global search page, for example `/search?term=mitoc`.
4. Verify that the …
> refactor: rewrite jQuery stuff in plain JavaScript

- api/src/neo4j/queries/search/globalSearch.js
- api/test/searchGlobal.test.js
This PR closes #1282.
Prevent empty (`{ score: 0 }`) results from being returned.
**Testing**  
1. Visit `/search?term=Herc1`.
2. Click the `Metabolites` tab and scroll to the bottom.
3. Verify that there are **no** empty rows being rendered.
4. Click the Genes tab and make sure that there are no rows with empty values for Subsystem or Compartment.
5. Please repeat the above steps for some other search terms.
There is a weird behavior with the cypher query in `fetchGenes` that could randomly drop subsystems or compartments. It seems that when the sub-queries …
> fix: do not include empty results for global search

- frontend/src/router.js
**Related issue(s) and PR(s)** 
This PR closes #1292.
- Updated redirects for map-viewer so that users end up at right URL without component and subsystem keywords
- Update redirects for map-viewer and genome-browser so that users are redirected to the respective resources rather than ending up in an endless loading page
In short:
- Check for when only gem browser or map viewer is visited
- Make sure the compartment and subsystem keywords are dropped
**Testing**  
Navigate to:
- [/explore/map-viewer/human1/compartment/endoplasmic_reticulum?dim=2d](https://www.metabolicatlas.org/explore/map-viewer/human1/compartment/endoplasmic_reticulum?dim=2d).
- [/explore/map-viewer/human1/)
- [/explore/gem-browser/human1/)
> Fix redirects for gem browser and map viewer

- docker-compose-local.yml
- proj.sh
fix: move neo4j imports to untouched container directory and update import-db
This PR closes #1303
It moves the data import files for neo4j from `/var/lib/neo4j/import` to `/opt/neo4j-import` in order to prevent the container from changing the permissions when running.
- Updates `docker-compose-local.yml` to use `/opt/neo4j-import` for imports
- Updates `proj.sh` to use the new import directory
**Testing**  
- Reset your `neo4j/import` directory
- Follow setup instructions
- Run `start-stack`
- Run `import-db`
- Expect the database to imported properly
> fix: move neo4j imports to untouched container directory

- api/src/neo4j/queries/idInModels.js
- api/test/externalDb.test.js
- frontend/src/components/IdInModels.vue
This PR closes #1309
- Sort `components` result from `/external-db/:dbName/:externalId` api endpoint
- Remove sorting from frontend component for `/identifier/:dbName/:identifierId`
**Testing**  
- Checkout and build project
- Verify that the order is correct in the frontend
- Use any tool to verify that the backend returns the components in the correct order: `curl http://localhost/api/v2/external-db/BiGG/PPNCL3 | jq`
- Run test: `ma-exec api yarn test test/externalDB.test.js`
> fix: move sorting from frontend to backend for external-db-endpoint

- frontend/src/components/explorer/interactionPartners/DetailsPage.vue
This PR closes #1168 
Changed the order of things when expanding interaction partner nodes. Instead of loading the data into the store first and trying to get routes correct later, navigate to new route first and load expansions from query params. 
- Context action (_Expand Interaction Partners_) click navigates to new route instead of loading expansions
- On new params expansions are reset and reloaded (just as if following a deep link to this expansion state) 
Note that this could possibly affect performance as expansions are reloaded even if already present in store, but compared to production the same requests seem to be made so it seems this behavior is not changed. 
**Screenshot of the fix** …
> Feature: Navigate to new route when expanding IP node to get browser history correct

- api/src/endpoints/dataOverlay.js
- api/src/endpoints/repository.js
- api/src/neo4j/queries/relatedMetabolites.js
- api/test/dataOverlay.test.js
- api/test/metabolites.test.js
- api/test/repository.test.js
- frontend/src/store/modules/gems.js
- frontend/src/store/modules/models.js
This PR closes #609
- Move sorting from frontend to backend
- Frontend views no longer sorts entries
- The following api entrypoints have been updated
- '/data-overlay/:model/:dataType/:filename/data-sets': sort names
- '/metabolites/:id/related-metabolites': sort by id
- '/repository/models': sort according to frontend method
- '/repository/integrated_models': sort according to frontend method
**Testing**  
- Make sure tests seem sane
- Make sure tests succeed `ma-exec api yarn test test/metabolites.test.js test/dataOverlay.test.js test/repository.test.js`
- Verify that navigating to metabolites from http://localhost/explore/Zebrafish-GEM/gem-browser works as expected
- Verifying that selecting overlay works …
> fix: move content sorting from frontend to api for relevant endpoints

- frontend/cypress/e2e/homepage.cy.js
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/mapViewer/IndicatorPanel.vue
- frontend/src/store/modules/dataOverlay.js
This PR closes #975
Adds a panel indicating the overlay data status
- Add an indicators getter to dataOverlay
- Add an indicator panel component
- Add indicator panel to mapviewer
**Testing**  
- Go to: http://localhost/explore/Human-GEM/map-viewer/acylglycerides_metabolism?dim=2d&panel=0&sel=&search=&coords=-1973.35,-3529.21,0.18,0,0,500&dataTypes=gene,reaction&dataSources=hpaRna.tsv,HPA_single-cell_reactions.tsv&dataSets=adrenal%20gland,adipose%20tissue_fibroblasts_0
- Look for the panel in the lower right corner
- Change the overlays and verify that it is updated
> feat: add overlay status indicator panel

- frontend/src/components/Home.vue
- frontend/src/components/explorer/MapViewer.vue
- frontend/src/components/explorer/interactionPartners/ContextMenu.vue
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/37 and relates to #1304 and #1313.
Removed CSS selectors that are not used.
**Testing**  
Check that the first page, Map Viewer and Interaction Partners pages work like expected.
The CSS selectors that are listed in #37 as unused have been tested to find out if this was the case. It turned out that some of them were actually used (see comments in #37).
> fix: remove unused css selectors

- api/src/neo4j/queries/idInModels.js
- api/src/swagger/config.yaml
- api/test/identifier.test.js
This PR closes #1331
It adds an identifier `url` to responses for `MetabolicAtlas` database items.
- Add `url` to responses with `dbName === 'MetabolicAtlas'`
**Example**
***command***
```sh
curl http://localhost/api/v2/identifier/MetabolicAtlas/MAR02279 | jq
```
***output***
```json
{
"components": [
{
"id": "MAR02279",
"model": "Fruitfly-GEM",
"componentType": "Reaction",
"version": "1.2.0"
},
{
"id": "MAR02279",
"model": "Human-GEM",
"componentType": "Reaction",
"version": "1.12.0"
},
{
"id": "MAR02279",
"model": "Mouse-GEM",
"componentType": "Reaction",
"version": "1.3.0"
},
{
"id": "MAR02279",
"model": "Rat-GEM",
"componentType": "Reaction",
"version": "1.3.0"
},
{
"id": "MAR02279",
"model": "Worm-GEM", …
```
> fix: Add `url` to `identifier` responses for MA ids

- README.md
- docker-compose-local.yml
- docker-compose-remote.yml
- pg/.dockerignore
- pg/Dockerfile
- proj.sh
This PR closes #1087 
Since the strategies are quite different from the draft PR #1275, a new branch and PR is created. 
Given the condition that the GotEnzymes input_data will not be changed frequently in the future, the following changes have been made to avoid frequent data transferring and rebuilding of the GotEnzymes database. 
1. `input_data` is not copied to the container but mounted at  `/var/lib/docker-volumes/pg/input_data/` for the remote server, by doing so, the size of the image `pg` is reduced from 3.04 GB to 216 MB. `input_data` is uploaded to the remote server by `rsync` and do not need to be transferred through docker at every deployment. 
2. For local deployment, the GotEnzymes database is …
> Chore: improve gotenzymes deployment
